# Generated by Django 2.1.3 on 2019-01-30 01:12

import A_dbms.models.m_appraisal
import A_dbms.models.m_warrant
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreeesExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_addr', models.CharField(max_length=64, verbose_name='联系地址')),
                ('linkman', models.CharField(max_length=16, verbose_name='联系人')),
                ('contact_num', models.CharField(max_length=13, verbose_name='联系电话')),
                ('registered_addr', models.CharField(blank=True, max_length=64, null=True, verbose_name='注册地址')),
                ('representative', models.CharField(blank=True, max_length=16, null=True, verbose_name='法人代表')),
                ('license_num', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
            ],
            options={
                'verbose_name_plural': '合同-委托合同扩展信息',
                'db_table': 'dbms_greeeExtend',
            },
        ),
        migrations.CreateModel(
            name='Agrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_num', models.CharField(max_length=32, unique=True, verbose_name='_合同编号')),
                ('num_prefix', models.CharField(max_length=32, verbose_name='_编号前缀')),
                ('agree_typ', models.IntegerField(choices=[(1, '单笔'), (2, '最高额'), (3, '保函')], verbose_name='合同种类')),
                ('guarantee_typ', models.CharField(choices=[('②', '②'), ('③', '③'), ('④', '④'), ('⑤', '⑤'), ('⑥', '⑥'), ('⑦', '⑦')], max_length=6, verbose_name='反担保种类数')),
                ('agree_copies', models.IntegerField(verbose_name='合同份数')),
                ('agree_amount', models.FloatField(verbose_name='合同金额')),
                ('agree_sign_date', models.DateField(blank=True, null=True, verbose_name='签批日期')),
                ('charge', models.FloatField(default=0, verbose_name='应收保费（元）')),
                ('ascertain_date', models.DateField(blank=True, null=True, verbose_name='落实日期')),
                ('agree_remark', models.TextField(blank=True, null=True, verbose_name='落实情况')),
                ('agree_state', models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '未落实'), (41, '已落实'), (51, '待变更'), (61, '已解保'), (99, '作废')], default=11, verbose_name='合同状态')),
                ('agree_notify_sum', models.FloatField(default=0, verbose_name='_通知金额')),
                ('agree_provide_sum', models.FloatField(default=0, verbose_name='_放款金额')),
                ('agree_repayment_sum', models.FloatField(default=0, verbose_name='_还款金额')),
                ('agree_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '合同',
                'db_table': 'dbms_agrees',
            },
        ),
        migrations.CreateModel(
            name='Appraisals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32, unique=True, verbose_name='评审会编号')),
                ('review_year', models.IntegerField(default=2019, verbose_name='评审年份')),
                ('review_order', models.IntegerField(verbose_name='评审次序')),
                ('review_model', models.IntegerField(choices=[(1, '内审'), (2, '外审')], verbose_name='评审类型')),
                ('review_date', models.DateField(default=datetime.date.today, verbose_name='评审日期')),
                ('meeting_state', models.IntegerField(choices=[(1, '待上会'), (2, '已上会')], default=1, verbose_name='会议状态')),
                ('meeting_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '评审',
                'db_table': 'dbms_appraisals',
            },
        ),
        migrations.CreateModel(
            name='ArticleChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_view', models.IntegerField(choices=[(1, '变更申请'), (11, '同意变更'), (21, '否决变更')], default=1, verbose_name='变更意见')),
                ('change_detail', models.TextField(verbose_name='签批详情')),
                ('change_date', models.DateField(verbose_name='变更日期')),
                ('build_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '项目-变更',
                'db_table': 'dbms_articlechange',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_num', models.CharField(max_length=32, unique=True, verbose_name='_项目编号')),
                ('renewal', models.FloatField(default=0, verbose_name='续贷金额（元）')),
                ('augment', models.FloatField(default=0, verbose_name='新增金额（元）')),
                ('amount', models.FloatField(default=0, verbose_name='_总额度（元）')),
                ('credit_term', models.IntegerField(default=12, verbose_name='授信期限（月）')),
                ('article_date', models.DateField(blank=True, null=True, verbose_name='反馈日期')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='上会日期')),
                ('summary_num', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='_纪要编号')),
                ('sign_type', models.IntegerField(blank=True, choices=[(1, '同意'), (2, '不同意')], null=True, verbose_name='签批结论')),
                ('rcd_opinion', models.TextField(blank=True, null=True, verbose_name='风控部意见')),
                ('convenor_opinion', models.TextField(blank=True, null=True, verbose_name='招集人意见')),
                ('sign_detail', models.TextField(blank=True, null=True, verbose_name='签批人意见')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签批日期')),
                ('article_state', models.IntegerField(choices=[(1, '待反馈'), (2, '已反馈'), (3, '待上会'), (4, '已上会'), (5, '已签批'), (51, '已放完'), (61, '待变更'), (99, '已注销')], default=1, verbose_name='_项目状态')),
                ('classification', models.IntegerField(choices=[(1, '正常'), (11, '关注'), (21, '次级'), (31, '可疑'), (41, '损失')], default=1, verbose_name='_风险分类')),
                ('article_provide_sum', models.FloatField(default=0, verbose_name='_放款金额')),
                ('article_repayment_sum', models.FloatField(default=0, verbose_name='_还款金额')),
                ('build_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '项目',
                'db_table': 'dbms_articles',
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='放款银行')),
                ('short_name', models.CharField(max_length=32, unique=True, verbose_name='银行简称')),
                ('branch_state', models.IntegerField(choices=[(1, '正常'), (2, '注销')], default=1, verbose_name='银行状态')),
                ('branch_flow', models.FloatField(default=0, verbose_name='_流贷余额')),
                ('branch_accept', models.FloatField(default=0, verbose_name='_承兑余额')),
                ('branch_back', models.FloatField(default=0, verbose_name='_保函余额')),
            ],
            options={
                'verbose_name_plural': '外部-放款银行',
                'db_table': 'dbms_branchess',
            },
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='收费金额')),
                ('balance', models.FloatField(verbose_name='应收余额')),
                ('charge_date', models.DateField(default=datetime.date.today, verbose_name='收费日期')),
                ('agree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_agree', to='A_dbms.Agrees', verbose_name='委托合同')),
            ],
            options={
                'verbose_name_plural': '放款-收费',
                'db_table': 'dbms_charges',
            },
        ),
        migrations.CreateModel(
            name='Chattel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chattel_typ', models.IntegerField(choices=[(1, '存货'), (11, '设备')], default=1, verbose_name='动产种类')),
                ('chattel_detail', models.TextField(verbose_name='动产具体描述')),
                ('chattel_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-动产',
                'db_table': 'dbms_rchattel',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(choices=[(1, '同意'), (2, '复议'), (3, '不同意')], default=1, verbose_name='评委意见')),
                ('concrete', models.TextField(verbose_name='意见详情')),
                ('comment_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '评审-意见',
                'db_table': 'dbms_comments',
            },
        ),
        migrations.CreateModel(
            name='Compensatories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensatory_date', models.DateField(default='2018-09-09', verbose_name='代偿日期')),
                ('compensatory_capital', models.FloatField(default=0, verbose_name='代偿本金')),
                ('compensatory_interest', models.FloatField(default=0, verbose_name='代偿利息')),
                ('retrieve_amount', models.FloatField(default=0, verbose_name='追偿总额')),
                ('dun_state', models.IntegerField(choices=[(1, '起诉'), (2, '判决'), (3, '执行'), (4, '和解结案'), (5, '终止执行')], default=1, verbose_name='追偿状态')),
            ],
            options={
                'verbose_name_plural': '追偿-代偿',
                'db_table': 'dbms_compensatories',
            },
        ),
        migrations.CreateModel(
            name='Cooperators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='合作机构')),
                ('short_name', models.CharField(max_length=32, unique=True, verbose_name='机构简称')),
                ('cooperator_state', models.IntegerField(choices=[(1, '金融机构'), (11, '律师事务所'), (21, '评估事务所')], default=1, verbose_name='机构类型')),
                ('flow_credit', models.FloatField(default=100000000, verbose_name='综合额度')),
                ('flow_limit', models.FloatField(default=10000000, verbose_name='单笔限额（综合）')),
                ('back_credit', models.FloatField(default=0, verbose_name='保函额度')),
                ('back_limit', models.FloatField(default=0, verbose_name='单笔限额（保函）')),
                ('credit_date', models.DateField(default=datetime.date.today, verbose_name='合作日期')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='到期日')),
            ],
            options={
                'verbose_name_plural': '外部-合作机构',
                'db_table': 'dbms_cooperators',
            },
        ),
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_num', models.CharField(max_length=32, unique=True, verbose_name='_合同编号')),
                ('counter_typ', models.IntegerField(choices=[(1, '企业担保'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (15, '车辆抵押'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='合同类型')),
                ('counter_copies', models.IntegerField(verbose_name='合同份数')),
                ('counter_state', models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '作废')], default=11, verbose_name='签订状态')),
                ('counter_sign_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('counter_remark', models.TextField(blank=True, null=True, verbose_name='签订备注')),
                ('counter_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('agree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counter_agree', to='A_dbms.Agrees', verbose_name='委托保证合同')),
            ],
            options={
                'verbose_name_plural': '合同-反担保',
                'db_table': 'dbms_counters',
            },
        ),
        migrations.CreateModel(
            name='CountersAssure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_assure_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('counter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assure_counter', to='A_dbms.Counters', verbose_name='反担保合同')),
            ],
            options={
                'verbose_name_plural': '合同-保证反担保',
                'db_table': 'dbms_countersassure',
            },
        ),
        migrations.CreateModel(
            name='CountersWarrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_warrant_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('counter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warrant_counter', to='A_dbms.Counters', verbose_name='反担保合同')),
            ],
            options={
                'verbose_name_plural': '合同-抵质押合同',
                'db_table': 'dbms_counterwarrants',
            },
        ),
        migrations.CreateModel(
            name='Customes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='客户名称')),
                ('short_name', models.CharField(max_length=16, unique=True, verbose_name='客户简称')),
                ('genre', models.IntegerField(choices=[(1, '企业'), (2, '个人')], default=1, verbose_name='客户类型')),
                ('contact_addr', models.CharField(max_length=64, verbose_name='联系地址')),
                ('linkman', models.CharField(max_length=16, verbose_name='联系人')),
                ('contact_num', models.CharField(max_length=13, verbose_name='联系电话')),
                ('review_plan_date', models.DateField(blank=True, null=True, verbose_name='保后计划')),
                ('review_state', models.IntegerField(choices=[(1, '待保后'), (11, '待报告'), (21, '已完成')], default=21, verbose_name='_保后状态')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='保后日期')),
                ('classification', models.IntegerField(blank=True, choices=[(1, '正常'), (11, '关注'), (21, '次级'), (31, '可疑'), (41, '损失')], null=True, verbose_name='_风险分类')),
                ('counter_only', models.BooleanField(default=1, verbose_name='仅反担保')),
                ('lately_date', models.DateField(blank=True, null=True, verbose_name='最近调查')),
                ('credit_amount', models.FloatField(default=0, verbose_name='_授信总额')),
                ('custom_flow', models.FloatField(default=0, verbose_name='_流贷余额')),
                ('custom_accept', models.FloatField(default=0, verbose_name='_承兑余额')),
                ('custom_back', models.FloatField(default=0, verbose_name='_保函余额')),
                ('custom_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '客户',
                'db_table': 'dbms_customes',
            },
        ),
        migrations.CreateModel(
            name='CustomesC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField(verbose_name='注册资本')),
                ('registered_addr', models.CharField(max_length=64, verbose_name='注册地址')),
                ('representative', models.CharField(max_length=16, verbose_name='法人代表')),
                ('custome', models.OneToOneField(limit_choices_to={'genre': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='company_custome', to='A_dbms.Customes', verbose_name='企业客户')),
            ],
            options={
                'verbose_name_plural': '客户-企业',
                'db_table': 'dbms_customesc',
            },
        ),
        migrations.CreateModel(
            name='CustomesP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_num', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('license_addr', models.CharField(max_length=64, verbose_name='身份证地址')),
                ('custome', models.OneToOneField(limit_choices_to={'genre': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='person_custome', to='A_dbms.Customes', verbose_name='个人客户')),
                ('spouse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_dbms.CustomesP', verbose_name='配偶')),
            ],
            options={
                'verbose_name_plural': '客户-个人',
                'db_table': 'dbms_customesp',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='部门名称')),
            ],
            options={
                'verbose_name_plural': '内部-部门',
                'db_table': 'dbms_departments',
            },
        ),
        migrations.CreateModel(
            name='Districtes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='街道名称')),
            ],
            options={
                'verbose_name_plural': '客户-区域',
                'db_table': 'dbms_districtes',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_detail', models.TextField(verbose_name='票据描述')),
                ('draft_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-应收票据',
                'db_table': 'dbms_draft',
            },
        ),
        migrations.CreateModel(
            name='DraftExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_typ', models.IntegerField(choices=[(1, '电子银行承兑汇票'), (2, '普通银行承兑汇票'), (11, '电子商业承兑汇票'), (12, '普通商业承兑汇票'), (21, '支票')], default=1, verbose_name='票据种类')),
                ('draft_num', models.CharField(max_length=64, verbose_name='票据编号')),
                ('draft_acceptor', models.CharField(max_length=64, verbose_name='承兑人')),
                ('draft_amount', models.FloatField(verbose_name='票面金额')),
                ('issue_date', models.DateField(verbose_name='出票日期')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('draft_e_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extend_draft', to='A_dbms.Draft', verbose_name='票据')),
            ],
            options={
                'verbose_name_plural': '权证-票据明细',
                'db_table': 'dbms_draftextend',
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluate_state', models.IntegerField(choices=[(1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本')], default=1, verbose_name='评估方式')),
                ('evaluate_value', models.FloatField(verbose_name='评估价值')),
                ('evaluate_date', models.DateField(verbose_name='评估日期')),
                ('evaluate_explain', models.CharField(blank=True, max_length=128, null=True, verbose_name='评估说明')),
                ('evaluator_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-评估',
                'db_table': 'dbms_evaluate',
            },
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='评审姓名')),
                ('organization', models.CharField(max_length=32, verbose_name='工作单位')),
                ('job', models.CharField(max_length=16, null=True, verbose_name='职务')),
                ('level', models.IntegerField(choices=[(1, '内部'), (2, '顾问'), (3, '一级'), (4, '二级')], default=1, verbose_name='级别')),
                ('contact_numb', models.CharField(max_length=16, unique=True, verbose_name='联系电话')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('ordery', models.IntegerField(verbose_name='优先级')),
                ('expert_state', models.IntegerField(choices=[(1, '正常'), (2, '注销')], default=1, verbose_name='评审状态')),
            ],
            options={
                'verbose_name_plural': '外部-评审专家',
                'db_table': 'dbms_experts',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propose', models.IntegerField(choices=[(1, '符合上会条件'), (11, '暂不符合上会条件'), (21, '建议终止项目')], verbose_name='上会建议')),
                ('analysis', models.TextField(verbose_name='风险分析')),
                ('suggestion', models.TextField(verbose_name='风控意见')),
                ('feedback_date', models.DateField(default=datetime.date.today, verbose_name='提交日期')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_article', to='A_dbms.Articles', verbose_name='项目')),
            ],
            options={
                'verbose_name_plural': '项目-反馈',
                'db_table': 'dbms_feedback',
            },
        ),
        migrations.CreateModel(
            name='Grounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_locate', models.CharField(max_length=64, verbose_name='土地坐落')),
                ('ground_app', models.IntegerField(choices=[(1, '住宅'), (5, '城镇混合住宅'), (11, '商住'), (21, '商服'), (31, '工业')], default=1, verbose_name='土地用途')),
                ('ground_area', models.FloatField(verbose_name='土地面积')),
                ('ground_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-土地',
                'db_table': 'dbms_grounds',
            },
        ),
        migrations.CreateModel(
            name='HouseBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housebag_locate', models.CharField(max_length=64, unique=True, verbose_name='房产坐落')),
                ('housebag_app', models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '厂房'), (51, '科研')], default=1, verbose_name='房产用途')),
                ('housebag_area', models.FloatField(verbose_name='建筑面积')),
                ('housebag_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-房产包',
                'db_table': 'dbms_housebag',
            },
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_locate', models.CharField(max_length=64, unique=True, verbose_name='房产坐落')),
                ('house_app', models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (51, '科研'), (61, '车库'), (71, '仓储'), (99, '期房')], default=1, verbose_name='房产用途')),
                ('house_area', models.FloatField(verbose_name='建筑面积')),
                ('house_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='楼盘名称')),
                ('house_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-房产',
                'db_table': 'dbms_houses',
            },
        ),
        migrations.CreateModel(
            name='Hypothecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothec_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('agree', models.ForeignKey(limit_choices_to=A_dbms.models.m_warrant.limit_agree_choices, on_delete=django.db.models.deletion.PROTECT, related_name='ypothec_agree', to='A_dbms.Agrees', verbose_name='委托合同')),
            ],
            options={
                'verbose_name_plural': '权证-他权',
                'db_table': 'dbms_hypothecs',
            },
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='行业编码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='行业名称')),
            ],
            options={
                'verbose_name_plural': '客户-行业',
                'db_table': 'dbms_industriess',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='岗位名称')),
            ],
            options={
                'verbose_name_plural': '内部-岗位',
                'db_table': 'dbms_jobs',
            },
        ),
        migrations.CreateModel(
            name='LendingCustoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_c_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('custome', models.ManyToManyField(related_name='lending_custom', to='A_dbms.Customes', verbose_name='反担保人')),
            ],
            options={
                'verbose_name_plural': '反担保-保证反担保',
                'db_table': 'dbms_lendingcustom',
            },
        ),
        migrations.CreateModel(
            name='LendingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(choices=[(1, '第一次'), (2, '第二次'), (3, '第三次'), (4, '第四次')], default=1, verbose_name='发放次序')),
                ('order_amount', models.FloatField(verbose_name='拟放金额')),
                ('lending_provide_sum', models.FloatField(default=0, verbose_name='_放款金额')),
                ('lending_repayment_sum', models.FloatField(default=0, verbose_name='_还款金额')),
                ('lending_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '评审-发放次序',
                'db_table': 'dbms_lending',
            },
        ),
        migrations.CreateModel(
            name='LendingSures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure_typ', models.IntegerField(choices=[(1, '企业保证'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (15, '车辆抵押'), (21, '房产顺位'), (22, '土地顺位'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (41, '合格证监管'), (42, '房产监管'), (43, '土地监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='担保类型')),
                ('sure_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sure_lending', to='A_dbms.LendingOrder', verbose_name='放款次序')),
            ],
            options={
                'verbose_name_plural': '反担保',
                'db_table': 'dbms_lendingsure',
            },
        ),
        migrations.CreateModel(
            name='LendingWarrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_w_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '反担保-抵质押',
                'db_table': 'dbms_lendingwarrant',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('url_name', models.CharField(max_length=128, verbose_name='URL')),
                ('ordery', models.IntegerField(verbose_name='优先级')),
            ],
            options={
                'verbose_name_plural': '内部-动态菜单',
                'db_table': 'dbms_menus',
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_money', models.FloatField(verbose_name='通知金额')),
                ('notify_date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('contracts_lease', models.CharField(blank=True, max_length=32, null=True, verbose_name='借款合同编号')),
                ('contract_guaranty', models.CharField(blank=True, max_length=32, null=True, verbose_name='保证合同编号')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('notify_provide_sum', models.FloatField(default=0, verbose_name='_放款金额')),
                ('notify_repayment_sum', models.FloatField(default=0, verbose_name='_还款金额')),
                ('agree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notify_agree', to='A_dbms.Agrees', verbose_name='委托保证合同')),
            ],
            options={
                'verbose_name_plural': '放款-放款通知',
                'db_table': 'dbms_notify',
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_num', models.CharField(max_length=32, unique=True, verbose_name='产权证编号')),
                ('ownership_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_custome', to='A_dbms.Customes', verbose_name='所有权人')),
            ],
            options={
                'verbose_name_plural': '权证-产权证',
                'db_table': 'dbms_ownership',
            },
        ),
        migrations.CreateModel(
            name='Pigeonholes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implement', models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档')], default=1, verbose_name='归档状态')),
                ('pigeonhole_date', models.DateField(default=datetime.date.today, verbose_name='归档日期')),
                ('pigeonhole_explain', models.CharField(blank=True, max_length=128, null=True, verbose_name='归档说明')),
            ],
            options={
                'verbose_name_plural': '放款-归档',
                'db_table': 'dbms_pigeonholes',
            },
        ),
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provide_typ', models.IntegerField(choices=[(1, '流贷'), (11, '承兑'), (21, '保函')], verbose_name='放款种类')),
                ('provide_money', models.FloatField(verbose_name='放款金额')),
                ('provide_date', models.DateField(verbose_name='放款日期')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('implement', models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档')], default=1, verbose_name='_归档状态')),
                ('file_num', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='档案编号')),
                ('provide_status', models.IntegerField(choices=[(1, '在保'), (11, '解保'), (21, '代偿')], default=1, verbose_name='_放款状态')),
                ('provide_repayment_sum', models.FloatField(default=0, verbose_name='_还款总额')),
                ('providordate', models.DateField(default=datetime.date.today, verbose_name='_创建日期')),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provide_notify', to='A_dbms.Notify', verbose_name='_放款通知')),
            ],
            options={
                'verbose_name_plural': '放款',
                'db_table': 'dbms_provides',
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivable_detail', models.TextField(verbose_name='应收账款描述')),
                ('receivable_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-应收账款',
                'db_table': 'dbms_receivable',
            },
        ),
        migrations.CreateModel(
            name='ReceiveExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_unit', models.CharField(max_length=64, verbose_name='应收单位名称')),
                ('receiv_e_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-应收明细',
                'db_table': 'dbms_receiveextend',
            },
        ),
        migrations.CreateModel(
            name='Repayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_money', models.FloatField(verbose_name='还款金额')),
                ('repayment_date', models.DateField(default=datetime.date.today, verbose_name='还款日期')),
                ('repaymentdate', models.DateField(default=datetime.date.today, verbose_name='_创建日期')),
                ('provide', models.ForeignKey(limit_choices_to={'provide_status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='repayment_provide', to='A_dbms.Provides', verbose_name='放款')),
            ],
            options={
                'verbose_name_plural': '项目-还款',
                'db_table': 'dbms_repayments',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_plan_date', models.DateField(blank=True, null=True, verbose_name='保后计划')),
                ('review_state', models.IntegerField(choices=[(1, '待保后'), (11, '待报告'), (21, '已完成')], default=1, verbose_name='_保后状态')),
                ('review_sty', models.IntegerField(blank=True, choices=[(1, '现场检查'), (11, '电话回访')], null=True, verbose_name='保后方式')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='风险分析')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='风控建议')),
                ('classification', models.IntegerField(blank=True, choices=[(1, '正常'), (11, '关注'), (21, '次级'), (31, '可疑'), (41, '损失')], null=True, verbose_name='风险分类')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='保后日期')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_custom', to='A_dbms.Customes', verbose_name='客户')),
            ],
            options={
                'verbose_name_plural': '项目-保后检查',
                'db_table': 'dbms_review',
            },
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(max_length=32, verbose_name='简称')),
                ('invested_amount', models.FloatField(verbose_name='投资额')),
                ('shareholding_ratio', models.FloatField(verbose_name='持股比例（%）')),
                ('shareholder_date', models.DateField(default=datetime.date.today, verbose_name='创建时间')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder_custom_c', to='A_dbms.CustomesC', verbose_name='企业客户')),
            ],
            options={
                'verbose_name_plural': '客户-股东信息',
                'db_table': 'dbms_shareholders',
            },
        ),
        migrations.CreateModel(
            name='SingleQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_model', models.IntegerField(choices=[(1, '流动资金贷款'), (2, '银行承兑汇票'), (3, '保函'), (4, '综合授信额度（含流贷、银承、保函）')], default=1, verbose_name='授信类型')),
                ('credit_amount', models.FloatField(verbose_name='授信额度（元）')),
                ('flow_rate', models.FloatField(verbose_name='费率（%）')),
                ('single_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '评审-额度',
                'db_table': 'dbms_single_quota',
            },
        ),
        migrations.CreateModel(
            name='Stockes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_typ', models.IntegerField(choices=[(1, '有限公司股权'), (11, '股份公司股份'), (21, '举办者权益')], default=1, verbose_name='股权性质')),
                ('target', models.CharField(max_length=64, verbose_name='标的公司')),
                ('share', models.FloatField(verbose_name='数量（万元/万股）')),
                ('stock_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-股权',
                'db_table': 'dbms_stockes',
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_typ', models.IntegerField(choices=[(1, '入库'), (2, '续抵出库'), (11, '借出'), (12, '归还'), (31, '解保出库')], default=1, verbose_name='出入库')),
                ('storage_explain', models.CharField(blank=True, max_length=128, null=True, verbose_name='出入库说明')),
                ('storage_date', models.DateField(default=datetime.date.today, verbose_name='出入库日期')),
            ],
            options={
                'verbose_name_plural': '权证-出入库',
                'db_table': 'dbms_storages',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_num', models.CharField(max_length=64, unique=True, verbose_name='车架号')),
                ('plate_num', models.CharField(max_length=64, unique=True, verbose_name='车牌号')),
                ('vehicle_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证-车辆',
                'db_table': 'dbms_vehicle',
            },
        ),
        migrations.CreateModel(
            name='Warrants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrant_num', models.CharField(max_length=128, unique=True, verbose_name='权证编码')),
                ('warrant_typ', models.IntegerField(choices=[(1, '房产'), (2, '房产包'), (5, '土地'), (11, '应收'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '动产'), (99, '他权')], default=1, verbose_name='权证类型')),
                ('evaluate_state', models.IntegerField(blank=True, choices=[(1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本')], null=True, verbose_name='评估方式')),
                ('evaluate_value', models.FloatField(blank=True, null=True, verbose_name='评估价值')),
                ('evaluate_date', models.DateField(blank=True, null=True, verbose_name='评估日期')),
                ('evaluate_explain', models.CharField(blank=True, max_length=128, null=True, verbose_name='评估说明')),
                ('warrant_state', models.IntegerField(choices=[(1, '未入库'), (2, '已入库'), (6, '无需入库'), (11, '续抵出库'), (21, '已借出'), (31, '解保出库'), (99, '已注销')], default=1, verbose_name='_权证状态')),
                ('storage_explain', models.CharField(blank=True, max_length=128, null=True, verbose_name='出入库说明')),
                ('warrant_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '权证',
                'db_table': 'dbms_warrants',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'email already exists.'}, max_length=150, unique=True, verbose_name='电子邮箱')),
                ('num', models.CharField(max_length=64, verbose_name='代码')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('employee_status', models.IntegerField(choices=[(1, '在职'), (11, '离职')], default=1, verbose_name='_放款状态')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_department', to='A_dbms.Departments', verbose_name='部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('job', models.ManyToManyField(blank=True, null=True, to='A_dbms.Jobs')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '内部-员工',
                'permissions': [('dbms_article_all', '访问项目列表'), ('dbms_article', '访问所有项目列表'), ('article_scan_all', '访问项目添加页'), ('article_scan_agree', '添加项目')],
                'db_table': 'dbms_employees',
            },
        ),
        migrations.AddField(
            model_name='warrants',
            name='warrant_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='warrant_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 41}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='storages',
            name='conservator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conservator_employee', to=settings.AUTH_USER_MODEL, verbose_name='权证管理岗'),
        ),
        migrations.AddField(
            model_name='storages',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_employee', to=settings.AUTH_USER_MODEL, verbose_name='移交/接收者'),
        ),
        migrations.AddField(
            model_name='storages',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='stockes',
            name='stock_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='stockes',
            name='stock_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_owner_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AddField(
            model_name='stockes',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 21}, on_delete=django.db.models.deletion.PROTECT, related_name='stock_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='singlequota',
            name='single_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='single_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='singlequota',
            name='summary',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_appraisal.limit_article_choices, on_delete=django.db.models.deletion.PROTECT, related_name='single_quota_summary', to='A_dbms.Articles', verbose_name='纪要'),
        ),
        migrations.AddField(
            model_name='shareholders',
            name='shareholderor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shareholderor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewor_employee', to=settings.AUTH_USER_MODEL, verbose_name='保后人员'),
        ),
        migrations.AddField(
            model_name='repayments',
            name='repaymentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='repaymentor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='receiveextend',
            name='receiv_e_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='receiv_e_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='receiveextend',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extend_receiveable', to='A_dbms.Receivable', verbose_name='应收账款'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='receivable_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='receive_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AddField(
            model_name='receivable',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 11}, on_delete=django.db.models.deletion.PROTECT, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='provides',
            name='providor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='pigeonhole_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeonhole_transfer_employee', to=settings.AUTH_USER_MODEL, verbose_name='移交人'),
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='pigeonholor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeonholor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeonhole_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='ownership_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ownership_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='notify',
            name='notifyor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifyor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AlterUniqueTogether(
            name='menus',
            unique_together={('name', 'url_name')},
        ),
        migrations.AddField(
            model_name='lendingwarrants',
            name='lending_w_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lending_w_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='lendingwarrants',
            name='sure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warrant_sure', to='A_dbms.LendingSures', verbose_name='反担保措施'),
        ),
        migrations.AddField(
            model_name='lendingwarrants',
            name='warrant',
            field=models.ManyToManyField(related_name='lending_warrant', to='A_dbms.Warrants', verbose_name='抵质押物'),
        ),
        migrations.AddField(
            model_name='lendingsures',
            name='sure_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sure_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='lendingorder',
            name='lending_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lending_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='lendingorder',
            name='summary',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_appraisal.limit_lending_choices, on_delete=django.db.models.deletion.PROTECT, related_name='lending_summary', to='A_dbms.Articles', verbose_name='项目纪要'),
        ),
        migrations.AddField(
            model_name='lendingcustoms',
            name='lending_c_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lending_c_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='lendingcustoms',
            name='sure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_sure', to='A_dbms.LendingSures', verbose_name='反担保措施'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='menu',
            field=models.ManyToManyField(blank=True, to='A_dbms.Menus', verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='hypothecs',
            name='hypothec_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hypothec_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 99}, on_delete=django.db.models.deletion.PROTECT, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AddField(
            model_name='hypothecs',
            name='warrant_m',
            field=models.ManyToManyField(related_name='ypothec_m_agree', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='houses',
            name='house_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='houses',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='house_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='housebag',
            name='housebag_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housebag_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='housebag',
            name='warrant',
            field=models.ForeignKey(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='housebag_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='grounds',
            name='ground_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ground_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='grounds',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 5}, on_delete=django.db.models.deletion.PROTECT, related_name='ground_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluate_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='draftextend',
            name='draft_e_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='draft_e_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='draft_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='draft',
            name='draft_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AddField(
            model_name='draft',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 31}, on_delete=django.db.models.deletion.PROTECT, related_name='draft_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='customesc',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custome_district', to='A_dbms.Districtes', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='customesc',
            name='idustry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custome_idustry', to='A_dbms.Industries', verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='customes',
            name='custom_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custom_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='counterswarrants',
            name='counter_warrant_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='counter_warrantor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='counterswarrants',
            name='warrant',
            field=models.ManyToManyField(related_name='counter_warrant', to='A_dbms.Warrants', verbose_name='抵质押物'),
        ),
        migrations.AddField(
            model_name='countersassure',
            name='counter_assure_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='counter_assureor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='countersassure',
            name='custome',
            field=models.ManyToManyField(related_name='counter_custome', to='A_dbms.Customes', verbose_name='反担保人'),
        ),
        migrations.AddField(
            model_name='counters',
            name='counter_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='counteror_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='compensatories',
            name='provide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='compensatory_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comment_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='comments',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_expert', to='A_dbms.Experts', verbose_name='评委'),
        ),
        migrations.AddField(
            model_name='comments',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_summary', to='A_dbms.Articles', verbose_name='纪要'),
        ),
        migrations.AddField(
            model_name='chattel',
            name='chattel_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='chattel_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='chattel',
            name='chattel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chattel_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AddField(
            model_name='chattel',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 51}, on_delete=django.db.models.deletion.PROTECT, related_name='chattel_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AddField(
            model_name='charges',
            name='charge_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='charge_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='branches',
            name='cooperator',
            field=models.ForeignKey(limit_choices_to={'cooperator_state': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='branch_cooperator', to='A_dbms.Cooperators', verbose_name='授信银行'),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='articles',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_employee', to=settings.AUTH_USER_MODEL, verbose_name='项目助理'),
        ),
        migrations.AddField(
            model_name='articles',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_employee', to=settings.AUTH_USER_MODEL, verbose_name='风控专员'),
        ),
        migrations.AddField(
            model_name='articles',
            name='custom',
            field=models.ForeignKey(limit_choices_to={'counter_only': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='article_custom', to='A_dbms.Customes', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='articles',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_employee', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AddField(
            model_name='articles',
            name='expert',
            field=models.ManyToManyField(related_name='article_expert', to='A_dbms.Experts', verbose_name='评审委员'),
        ),
        migrations.AddField(
            model_name='articlechange',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_article', to='A_dbms.Articles', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='articlechange',
            name='change_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='appraisals',
            name='article',
            field=models.ManyToManyField(blank=True, limit_choices_to={'article_state': 2}, null=True, related_name='appraisal_article', to='A_dbms.Articles', verbose_name='参评项目'),
        ),
        migrations.AddField(
            model_name='appraisals',
            name='meeting_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='agree_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agree_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agree_branch', to='A_dbms.Branches', verbose_name='放款银行'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='lending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agree_lending', to='A_dbms.LendingOrder', verbose_name='放款纪要'),
        ),
        migrations.AddField(
            model_name='agreeesextend',
            name='agree',
            field=models.OneToOneField(limit_choices_to={'counter_only': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='extend_agree', to='A_dbms.Agrees', verbose_name='委托合同'),
        ),
        migrations.AlterUniqueTogether(
            name='singlequota',
            unique_together={('summary', 'credit_model')},
        ),
        migrations.AlterUniqueTogether(
            name='shareholders',
            unique_together={('custom', 'shareholder_name')},
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('warrant', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='lendingorder',
            unique_together={('summary', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('summary', 'expert')},
        ),
        migrations.AlterUniqueTogether(
            name='branches',
            unique_together={('name', 'cooperator')},
        ),
    ]
