# Generated by Django 2.1.3 on 2018-12-15 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(choices=[(1, '第一次'), (2, '第二次'), (3, '第三次'), (4, '第四次')], default=1, verbose_name='发放次序')),
                ('order_amount', models.FloatField(verbose_name='拟放金额')),
                ('amount', models.FloatField(default=0, verbose_name='已放金额')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lending_summary', to='A_dbms.Articles', verbose_name='纪要')),
            ],
            options={
                'db_table': 'dbms_lending',
                'verbose_name_plural': '评审-发放次序',
            },
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='应收账款描述')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive_custome', to='A_dbms.Customes', verbose_name='所有权人')),
                ('warrant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证')),
            ],
            options={
                'db_table': 'dbms_stock',
                'verbose_name_plural': '反担保-应收账款',
            },
        ),
        migrations.RemoveField(
            model_name='agrees',
            name='article',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_typ',
            field=models.IntegerField(choices=[(1, '有限公司股权'), (2, '股份公司股份'), (3, '举办者权益')], default=1, verbose_name='股权性质'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.IntegerField(choices=[(2, '②'), (3, '③'), (4, '④'), (5, '⑤'), (6, '⑥'), (7, '⑦')], verbose_name='反担保种类数'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='lending',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agree_lending', to='A_dbms.LendingOrder', verbose_name='放款纪要'),
            preserve_default=False,
        ),
    ]
