# Generated by Django 2.1.7 on 2019-11-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counters',
            old_name='other',
            new_name='counter_other',
        ),
    ]
