# Generated by Django 2.1.3 on 2019-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='counter_only',
            field=models.BooleanField(default=1, verbose_name='仅反担保'),
            preserve_default=False,
        ),
    ]
