# Generated by Django 2.1.3 on 2018-12-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreeesextend',
            options={'verbose_name_plural': '合同-委托合同扩展信息'},
        ),
        migrations.AlterModelTable(
            name='agreeesextend',
            table='dbms_greee_extend',
        ),
    ]
