# Generated by Django 2.1.3 on 2018-12-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensatories',
            name='compensatory_num',
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(1, '待签批'), (2, '已签批'), (3, '已落实'), (4, '已注销')], default=1, verbose_name='_合同状态'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '已反馈'), (3, '待上会'), (4, '已上会'), (5, '已签批'), (6, '已注销')], default=1, verbose_name='项目状态'),
        ),
    ]
