# Generated by Django 2.1.3 on 2018-12-27 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customes',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customes',
            name='idustry',
        ),
        migrations.AddField(
            model_name='customesc',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custome_district', to='A_dbms.Districtes', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='customesc',
            name='idustry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custome_idustry', to='A_dbms.Industries', verbose_name='所属行业'),
        ),
    ]
