# Generated by Django 2.1.7 on 2019-11-25 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='签订日期'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (25, '已签订'), (31, '未落实'), (41, '已落实'), (51, '待变更'), (61, '已解保'), (99, '已注销')], default=11, verbose_name='合同状态'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 11, 25), verbose_name='补调日期'),
        ),
    ]
