# Generated by Django 2.1.3 on 2019-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seal',
            options={'verbose_name_plural': '追偿-查封现状'},
        ),
        migrations.AlterModelOptions(
            name='sealup',
            options={'verbose_name_plural': '追偿-查封明细'},
        ),
        migrations.AddField(
            model_name='seal',
            name='inquiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='_最近查询日'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='_查封到期日'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='seal_date',
            field=models.DateField(blank=True, null=True, verbose_name='_最近查封日'),
        ),
    ]
