# Generated by Django 2.1.7 on 2019-10-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_typ',
        ),
    ]
