# Generated by Django 2.1.3 on 2019-02-02 03:22

import A_dbms.models.m_agree
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='time_limit',
            field=models.IntegerField(default=12, verbose_name='期限（月）'),
        ),
        migrations.AddField(
            model_name='notify',
            name='weighting',
            field=models.FloatField(default=0, verbose_name='加权金额'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agrees',
            name='lending',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_agree.limit_agree_choices, on_delete=django.db.models.deletion.PROTECT, related_name='agree_lending', to='A_dbms.LendingOrder', verbose_name='放款纪要'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, related_name='appraisal_article', to='A_dbms.Articles', verbose_name='参评项目'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (61, '车库'), (71, '仓储'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
    ]
