# Generated by Django 2.1.3 on 2018-12-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingSures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure_typ', models.IntegerField(choices=[(0, '--------'), (1, '个人保证'), (2, '企业保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '设备抵押'), (14, '存货抵押'), (15, '车辆抵押'), (21, '房产顺位'), (22, '土地顺位'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (41, '合格证监管'), (42, '房产监管'), (43, '土地监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='担保类型')),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sure_lending', to='A_dbms.LendingOrder', verbose_name='放款次序')),
            ],
            options={
                'db_table': 'dbms_lendingsure',
                'verbose_name_plural': '反担保-反担保措施',
            },
        ),
        migrations.CreateModel(
            name='MortgageExtends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mortgage_sure', to='A_dbms.LendingSures', verbose_name='反担保措施')),
            ],
            options={
                'db_table': 'dbms_mortgage_extend',
                'verbose_name_plural': '反担保-抵质押',
            },
        ),
        migrations.CreateModel(
            name='SureExtends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custome', models.ManyToManyField(related_name='sure_custome', to='A_dbms.Customes', verbose_name='反担保人')),
                ('sure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sure_sure', to='A_dbms.LendingSures', verbose_name='反担保措施')),
            ],
            options={
                'db_table': 'dbms_sure_extend',
                'verbose_name_plural': '反担保-保证反担保',
            },
        ),
        migrations.AlterField(
            model_name='grounds',
            name='ground_app',
            field=models.IntegerField(choices=[(1, '住宅'), (2, '商住'), (3, '商服'), (4, '工业')], default=1, verbose_name='土地用途'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='ground_area',
            field=models.FloatField(verbose_name='土地面积'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='ground_locate',
            field=models.CharField(max_length=64, verbose_name='土地坐落'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (2, '商业'), (3, '办公'), (4, '公寓'), (5, '厂房'), (6, '科研')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_locate',
            field=models.CharField(max_length=64, unique=True, verbose_name='房产坐落'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_num',
            field=models.CharField(max_length=32, unique=True, verbose_name='权证编码'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '土地'), (3, '应收'), (4, '股权'), (5, '票据'), (6, '车辆'), (7, '其他'), (8, '他权')], default=1, verbose_name='权证类型'),
        ),
        migrations.AddField(
            model_name='mortgageextends',
            name='warrant',
            field=models.ManyToManyField(related_name='mortgage_warrant', to='A_dbms.Warrants', verbose_name='抵质押物'),
        ),
    ]
