# Generated by Django 2.1.3 on 2019-01-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterswarrants',
            options={'verbose_name_plural': '合同-抵质押合同'},
        ),
        migrations.AlterModelOptions(
            name='receiveextend',
            options={'verbose_name_plural': '权证-应收明细'},
        ),
        migrations.AddField(
            model_name='customes',
            name='counter_only',
            field=models.BooleanField(default=1, verbose_name='仅反担保'),
        ),
        migrations.AlterModelTable(
            name='receiveextend',
            table='dbms_receiveextend',
        ),
    ]
