# Generated by Django 2.1.3 on 2018-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '待上会'), (3, '已上会'), (4, '已签批'), (5, '出合同'), (6, '已放款'), (7, '已归档'), (8, '已解保'), (9, '已代偿')], default=1, verbose_name='项目状态'),
        ),
    ]
