# Generated by Django 2.1.3 on 2018-12-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterswarrants',
            name='counter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warrant_counter', to='A_dbms.Counters', verbose_name='反担保合同'),
        ),
    ]
