# Generated by Django 2.1.3 on 2019-01-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='custom',
            field=models.ForeignKey(limit_choices_to={'counter_only': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='article_custom', to='A_dbms.Customes', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='credit_amount',
            field=models.FloatField(default=0, verbose_name='_授信总额'),
        ),
    ]
