# Generated by Django 2.1.7 on 2019-11-26 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='repay_method',
            new_name='article_repay_method',
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 11, 26), verbose_name='补调日期'),
        ),
    ]
