# Generated by Django 2.1.3 on 2018-11-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='menus',
            field=models.ManyToManyField(blank=True, to='A_dbms.Menus', verbose_name='菜单'),
        ),
    ]
