# Generated by Django 2.1.3 on 2018-12-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='receivable',
            table='dbms_receivable',
        ),
    ]
