# Generated by Django 2.1.3 on 2018-12-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20181223_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluate',
            options={'verbose_name_plural': '权证-评估'},
        ),
        migrations.AlterModelOptions(
            name='grounds',
            options={'verbose_name_plural': '权证-土地'},
        ),
        migrations.AlterModelOptions(
            name='houses',
            options={'verbose_name_plural': '权证-房产'},
        ),
        migrations.AlterModelOptions(
            name='hypothecs',
            options={'verbose_name_plural': '权证-他权'},
        ),
        migrations.AlterModelOptions(
            name='ownership',
            options={'verbose_name_plural': '权证-产权证'},
        ),
        migrations.AlterModelOptions(
            name='receivable',
            options={'verbose_name_plural': '权证-应收账款'},
        ),
        migrations.AlterModelOptions(
            name='stockes',
            options={'verbose_name_plural': '权证-股权'},
        ),
        migrations.AlterModelOptions(
            name='storages',
            options={'verbose_name_plural': '权证-出入库'},
        ),
        migrations.AlterModelOptions(
            name='warrants',
            options={'verbose_name_plural': '权证-权证'},
        ),
    ]
