# Generated by Django 2.1.3 on 2018-12-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20181227_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='counter_typ',
            field=models.IntegerField(choices=[(1, '企业担保'), (2, '个人担保'), (3, '房产抵押'), (4, '土地抵押'), (5, '应收质押'), (6, '动产抵押'), (7, '车辆抵押')], verbose_name='合同类型'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='agree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ypothec_agree', to='A_dbms.Agrees', verbose_name='委托合同'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '土地'), (3, '应收'), (4, '股权'), (5, '票据'), (6, '车辆'), (7, '其他'), (9, '他权')], default=1, verbose_name='权证类型'),
        ),
    ]
