# Generated by Django 2.1.7 on 2020-01-03 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20191220_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fic_date', models.DateField(default=datetime.date.today, verbose_name='分类期间')),
                ('fication', models.IntegerField(choices=[(11, '正常'), (21, '关注'), (31, '次级'), (41, '可疑'), (51, '损失')], default=11, verbose_name='五级分类')),
                ('explain', models.TextField(blank=True, null=True, verbose_name='分类说明')),
                ('ficationdate', models.DateField(default=datetime.date.today, verbose_name='分类日期')),
                ('ficationor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ficationor_employee', to=settings.AUTH_USER_MODEL, verbose_name='分类人员')),
            ],
            options={
                'verbose_name_plural': '保后-分类',
                'db_table': 'dbms_fication',
            },
        ),
        migrations.AddField(
            model_name='provides',
            name='fic_date',
            field=models.DateField(default=datetime.date.today, verbose_name='分类日期'),
        ),
        migrations.AddField(
            model_name='provides',
            name='fication',
            field=models.IntegerField(choices=[(11, '正常'), (21, '关注'), (31, '次级'), (41, '可疑'), (51, '损失')], default=11, verbose_name='风险分类'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='review_year',
            field=models.IntegerField(default=2020, verbose_name='评审年份'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='linkman',
            field=models.CharField(max_length=64, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date.today, verbose_name='补调日期'),
        ),
        migrations.AddField(
            model_name='fication',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fication_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
    ]
