# Generated by Django 2.1.3 on 2018-12-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20181219_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customesc',
            name='custome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_custome', to='A_dbms.Customes', verbose_name='企业客户'),
        ),
        migrations.AlterField(
            model_name='customesp',
            name='custome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_custome', to='A_dbms.Customes', verbose_name='个人客户'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
