# Generated by Django 2.1.3 on 2019-01-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20190103_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customesc',
            name='custome',
            field=models.OneToOneField(limit_choices_to={'genre': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='company_custome', to='A_dbms.Customes', verbose_name='企业客户'),
        ),
        migrations.AlterField(
            model_name='customesp',
            name='custome',
            field=models.OneToOneField(limit_choices_to={'genre': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='person_custome', to='A_dbms.Customes', verbose_name='个人客户'),
        ),
    ]
