# Generated by Django 2.1.3 on 2018-12-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20181215_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.IntegerField(choices=[('②', '②'), ('③', '③'), ('④', '④'), ('⑤', '⑤'), ('⑥', '⑥'), ('⑦', '⑦')], verbose_name='反担保种类数'),
        ),
    ]
