# Generated by Django 2.1.3 on 2019-01-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_customes_counter_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customes',
            name='counter_only',
            field=models.BooleanField(default=1, verbose_name='仅反担保'),
        ),
    ]
