# Generated by Django 2.1.7 on 2019-10-16 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_remove_articles_article_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='currentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_currentor_employee', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人'),
        ),
        migrations.AddField(
            model_name='articles',
            name='frontor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_frontor_employee', to=settings.AUTH_USER_MODEL, verbose_name='上一审批人'),
        ),
        migrations.AddField(
            model_name='articles',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_process', to='A_dbms.Process', verbose_name='审批流程'),
        ),
        migrations.AddField(
            model_name='articles',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_product', to='A_dbms.Product', verbose_name='产品种类'),
        ),
    ]
