# Generated by Django 2.1.3 on 2018-12-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20181209_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agreeesextend',
            table='dbms_greeeExtend',
        ),
    ]
