# Generated by Django 2.1.7 on 2019-11-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20191125_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='repay_method',
            field=models.IntegerField(blank=True, choices=[(11, '按月付息、到期一次还本'), (21, '等额本息'), (31, '按月付息、分期还本')], null=True, verbose_name='还款方式'),
        ),
    ]
