# Generated by Django 2.1.3 on 2019-02-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20190222_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgment',
            name='judgment_remark',
        ),
    ]
