# Generated by Django 2.1.3 on 2018-12-31 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0002_auto_20181230_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counters',
            old_name='agree_buildor',
            new_name='counter_buildor',
        ),
    ]
