# Generated by Django 2.1.3 on 2019-01-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190103_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivable',
            old_name='detail',
            new_name='receivable_detail',
        ),
        migrations.AlterField(
            model_name='countersassure',
            name='counter',
            field=models.OneToOneField(limit_choices_to={'article_state__in': [1, 2, 3, 4]}, on_delete=django.db.models.deletion.PROTECT, related_name='assure_counter', to='A_dbms.Counters', verbose_name='反担保合同'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='ground_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='house_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='lendingorder',
            name='summary',
            field=models.ForeignKey(limit_choices_to={'counter_typ__in': [1, 2]}, on_delete=django.db.models.deletion.PROTECT, related_name='lending_summary', to='A_dbms.Articles', verbose_name='项目纪要'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
