# Generated by Django 2.1.3 on 2018-12-07 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181207_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propose', models.IntegerField(choices=[(1, '符合上会条件'), (2, '暂不符合上会条件'), (3, '建议终止项目')], default=1, verbose_name='上会建议')),
                ('suggestion', models.TextField(verbose_name='风控意见')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_article', to='A_dbms.Articles', verbose_name='项目')),
                ('feedback_buildor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
