# Generated by Django 2.1.3 on 2019-02-22 08:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_remove_judgment_judgment_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_detail', models.TextField(verbose_name='判决内容')),
                ('standing_date', models.DateField(verbose_name='判决日期')),
                ('standingor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('dun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standing_dun', to='A_dbms.Dun', verbose_name='追偿项目')),
                ('standingor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standingor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'dbms_standing',
                'verbose_name_plural': '追偿-周报',
            },
        ),
    ]
