# Generated by Django 2.1.3 on 2018-12-28 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181227_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='storages',
            name='storage_builder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='storage_employee', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='storage_typ',
            field=models.IntegerField(choices=[(1, '入库'), (2, '出库'), (3, '借出'), (4, '归还'), (5, '解保')], default=1, verbose_name='出入库'),
        ),
    ]
