# Generated by Django 2.1.3 on 2018-12-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='level',
            field=models.IntegerField(choices=[(1, '内部'), (2, '顾问'), (3, '一级'), (4, '二级')], default=1, verbose_name='级别'),
        ),
    ]
