# Generated by Django 2.1.3 on 2018-12-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181224_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='上会日期'),
        ),
    ]
