# Generated by Django 2.1.3 on 2019-07-10 00:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190705_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['stage_type', 'stage_remark'], 'verbose_name_plural': '追偿-追偿阶段'},
        ),
        migrations.AddField(
            model_name='customes',
            name='controler',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.PROTECT, related_name='controler_employee', to=settings.AUTH_USER_MODEL, verbose_name='风控专员'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 7, 10), verbose_name='补调日期'),
        ),
    ]
