# Generated by Django 2.1.3 on 2018-12-31 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181231_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='evaluator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluator_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
