# Generated by Django 2.1.3 on 2018-12-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181209_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customesc',
            name='license_num',
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_typ',
            field=models.IntegerField(choices=[(0, '--------'), (1, '企业担保'), (2, '个人担保'), (3, '房产抵押'), (4, '土地抵押'), (5, '应收质押'), (6, '动产抵押'), (7, '车辆抵押')], verbose_name='合同类型'),
        ),
    ]
