# Generated by Django 2.1.3 on 2019-01-05 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190105_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_employee', to=settings.AUTH_USER_MODEL, verbose_name='项目助理'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_employee', to=settings.AUTH_USER_MODEL, verbose_name='风控专员'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_employee', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
    ]
