# Generated by Django 2.1.3 on 2018-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181206_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(1, '待签批'), (2, '已签批'), (3, '已落实'), (4, '已注销')], default=1, verbose_name='_合同状态'),
        ),
    ]
