# Generated by Django 2.1.3 on 2018-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181117_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='url_type',
        ),
        migrations.AddField(
            model_name='menus',
            name='ordery',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
