# Generated by Django 2.1.7 on 2020-01-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20200103_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customes',
            name='classification',
            field=models.IntegerField(choices=[(11, '正常'), (21, '关注'), (31, '次级'), (41, '可疑'), (51, '损失')], default=11, verbose_name='五级分类'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='custom_dun_state',
            field=models.IntegerField(choices=[(1, '正常'), (11, '被告'), (99, '注销')], default=11, verbose_name='_风险分类'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='i_classification',
            field=models.IntegerField(blank=True, choices=[(11, '正常'), (21, '关注'), (31, '次级'), (41, '可疑'), (51, '损失')], null=True, verbose_name='风险分类'),
        ),
        migrations.AlterField(
            model_name='review',
            name='classification',
            field=models.IntegerField(blank=True, choices=[(11, '正常'), (21, '关注'), (31, '次级'), (41, '可疑'), (51, '损失')], null=True, verbose_name='风险分类'),
        ),
    ]
