# Generated by Django 2.1.3 on 2019-01-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190102_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiveextend',
            options={'verbose_name_plural': '权证-应收明细'},
        ),
        migrations.AlterModelTable(
            name='receiveextend',
            table='dbms_receiveextend',
        ),
    ]
