# Generated by Django 2.1.4 on 2018-12-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181208_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_copies',
            field=models.IntegerField(default=4, verbose_name='合同份数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.IntegerField(choices=[(2, '②'), (3, '③'), (4, '④'), (5, '⑤'), (6, '③'), (7, '③')], default=4, verbose_name='反担保种类数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(1, '待签批'), (2, '已签批'), (3, '已落实'), (4, '已放款'), (5, '已解保'), (6, '已作废')], default=1, verbose_name='_合同状态'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_typ',
            field=models.IntegerField(choices=[(1, '单笔'), (2, '最高额'), (3, '保函')], verbose_name='合同种类'),
        ),
    ]
