# Generated by Django 2.1.3 on 2018-12-17 10:39

import A_dbms.models.m_appraisal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20181215_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='area_structure',
            new_name='house_area',
        ),
        migrations.AlterField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.CharField(choices=[('②', '②'), ('③', '③'), ('④', '④'), ('⑤', '⑤'), ('⑥', '⑥'), ('⑦', '⑦')], max_length=6, verbose_name='反担保种类数'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='lending',
            field=models.ForeignKey(limit_choices_to={'summary__article_state': 5}, on_delete=django.db.models.deletion.PROTECT, related_name='agree_lending', to='A_dbms.LendingOrder', verbose_name='放款纪要'),
        ),
        migrations.AlterField(
            model_name='lendingorder',
            name='summary',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_appraisal.limit_lending_choices, on_delete=django.db.models.deletion.PROTECT, related_name='lending_summary', to='A_dbms.Articles', verbose_name='纪要'),
        ),
    ]
