# Generated by Django 2.1.3 on 2019-02-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190226_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='成交日期'),
        ),
        migrations.AddField(
            model_name='warrants',
            name='transaction_date',
            field=models.DateField(blank=True, null=True, verbose_name='成交日期'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='auction_state',
            field=models.IntegerField(choices=[(1, '正常'), (5, '挂网'), (11, '成交'), (21, '流拍'), (31, '回转'), (99, '注销')], default=1, verbose_name='拍卖状态'),
        ),
    ]
