# Generated by Django 2.1.3 on 2019-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190408_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='counter_name',
            field=models.IntegerField(blank=True, choices=[(1, '保证反担保合同'), (2, '不可撤销的反担保函'), (3, '抵押反担保合同'), (4, '应收账款质押反担保合同'), (5, '股权质押反担保合同'), (6, '质押反担保合同'), (9, '预售合同'), (21, '最高额保证反担保合同'), (23, '最高额抵押反担保合同'), (24, '最高额应收账款质押反担保合同'), (25, '最高额股权质押反担保合同'), (26, '最高额质押反担保合同'), (41, '保证合同'), (43, '抵押合同'), (44, '应收账款质押合同'), (45, '股权质押合同'), (46, '质押合同')], null=True, verbose_name='合同种类'),
        ),
    ]
