# Generated by Django 2.1.3 on 2019-02-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0003_auto_20190202_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_term',
            field=models.IntegerField(default=12, verbose_name='合同期限（月）'),
        ),
    ]
