# Generated by Django 2.1.3 on 2018-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20181211_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customesc',
            name='capital',
            field=models.FloatField(default=1000000, verbose_name='注册资本（股本）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warrants',
            name='evaluate_date',
            field=models.DateField(blank=True, null=True, verbose_name='评估日期'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='evaluate_value',
            field=models.FloatField(blank=True, null=True, verbose_name='评估价值'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_state',
            field=models.IntegerField(choices=[(1, '未入库'), (2, '已入库'), (3, '已出库'), (4, '已借出'), (5, '已归还'), (6, '已注销')], default=1, verbose_name='_权证状态'),
        ),
    ]
