# Generated by Django 2.1.3 on 2019-02-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20190226_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='evaluate_date',
            field=models.DateField(blank=True, null=True, verbose_name='评估日期'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='evaluate_value',
            field=models.FloatField(blank=True, null=True, verbose_name='评估价值'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='auction_state',
            field=models.IntegerField(choices=[(1, '正常'), (3, '评估'), (11, '成交'), (21, '流拍'), (31, '回转'), (99, '注销')], default=1, verbose_name='拍卖状态'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='evaluate_state',
            field=models.IntegerField(blank=True, choices=[(1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本'), (41, '拍卖评估')], null=True, verbose_name='评估方式'),
        ),
    ]
