# Generated by Django 2.1.3 on 2018-12-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20181217_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='application',
            new_name='house_app',
        ),
    ]
