# Generated by Django 2.1.3 on 2019-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20190105_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='amount',
            field=models.FloatField(default=0, verbose_name='_总额度（元）'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='augment',
            field=models.FloatField(default=0, verbose_name='新增金额（元）'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='renewal',
            field=models.FloatField(default=0, verbose_name='续贷金额（元）'),
        ),
    ]
