# Generated by Django 2.1.3 on 2019-02-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_agrees_agree_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='agree_term',
            field=models.IntegerField(verbose_name='合同期限（月）'),
        ),
    ]
