# Generated by Django 2.1.3 on 2018-12-28 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20181228_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='storages',
            name='transfer_builder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_employee', to=settings.AUTH_USER_MODEL, verbose_name='移交/接收者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storages',
            name='storage_builder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_employee', to=settings.AUTH_USER_MODEL, verbose_name='权证管理岗'),
        ),
    ]
