# Generated by Django 2.1.7 on 2019-10-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20191018_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='typ',
            field=models.IntegerField(choices=[(1, '签批 '), (11, '内审'), (21, '外审')], default=1, verbose_name='流程类型'),
        ),
    ]
