# Generated by Django 2.1.3 on 2019-01-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20190103_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattel',
            old_name='detail',
            new_name='chattel_detail',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='detail',
            new_name='rraft_detail',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='owner',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.ForeignKey(default=1, limit_choices_to={'warrant_typ': 7}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_custome', to='A_dbms.Customes', verbose_name='所有权人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draft',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='draft_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 6}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
