# Generated by Django 2.1.3 on 2018-12-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': '项目-项目'},
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='dbms_feedback',
        ),
    ]
