# Generated by Django 2.1.4 on 2018-12-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20181209_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrees',
            name='agree_order',
        ),
        migrations.AlterField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.CharField(choices=[('②', '②'), ('③', '③'), ('④', '④'), ('⑤', '⑤'), ('⑥', '⑥'), ('⑦', '⑦')], max_length=4, verbose_name='反担保种类数'),
        ),
    ]
