# Generated by Django 2.1.3 on 2018-11-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20181117_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='A_dbms.Departments'),
        ),
    ]
