# Generated by Django 2.1.7 on 2020-01-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_auto_20200103_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='agree_rate',
            field=models.TextField(verbose_name='收费（利率）'),
        ),
    ]
