# Generated by Django 2.1.3 on 2018-12-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0004_evaluate_evaluator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chattel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chattel_typ', models.IntegerField(choices=[(1, '存货'), (2, '设备')], default=1, verbose_name='动产种类')),
                ('detail', models.TextField(verbose_name='动产具体描述')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chattel_custome', to='A_dbms.Customes', verbose_name='所有权人')),
                ('warrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chattel_warrant', to='A_dbms.Warrants', verbose_name='权证')),
            ],
            options={
                'verbose_name_plural': '权证-动产',
                'db_table': 'dbms_rchattel',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_num', models.CharField(max_length=64, unique=True, verbose_name='车架号')),
                ('plate_num', models.CharField(max_length=64, unique=True, verbose_name='车牌号')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_custome', to='A_dbms.Customes', verbose_name='所有权人')),
                ('warrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_warrant', to='A_dbms.Warrants', verbose_name='权证')),
            ],
            options={
                'verbose_name_plural': '权证-车辆',
                'db_table': 'dbms_vehicle',
            },
        ),
    ]
