# Generated by Django 2.1.7 on 2020-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20200115_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftextend',
            name='draft_state',
            field=models.IntegerField(choices=[(1, '未入库'), (2, '已入库'), (21, '置换出库'), (31, '解保出库'), (41, '托收出库'), (99, '已注销')], default=1, verbose_name='票据状态'),
        ),
    ]
