# Generated by Django 2.1.3 on 2018-12-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20181224_2100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lendingcustoms',
            table='dbms_lendingcustom',
        ),
        migrations.AlterModelTable(
            name='lendingwarrants',
            table='dbms_lendingwarrant',
        ),
    ]
