# Generated by Django 2.1.3 on 2019-02-23 06:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190223_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='seal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_state', models.IntegerField(choices=[(1, '未查封'), (11, '已查封'), (99, '已解封')], default=1, verbose_name='查封状态')),
                ('seal_date', models.DateField(blank=True, null=True, verbose_name='首封日期')),
                ('sequest_date', models.DateField(blank=True, null=True, verbose_name='最近查封日')),
                ('sequest_term', models.DateField(blank=True, null=True, verbose_name='查封期限(月)')),
                ('seal_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('sealor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('dun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seal_dun', to='A_dbms.Dun', verbose_name='追偿项目')),
                ('sealor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sealor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('warrant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seal_warrant', to='A_dbms.Warrants', verbose_name='财产')),
            ],
            options={
                'db_table': 'dbms_seal',
                'verbose_name_plural': '追偿-财产',
            },
        ),
        migrations.AlterUniqueTogether(
            name='seal',
            unique_together={('dun', 'warrant')},
        ),
    ]
