# Generated by Django 2.1.3 on 2018-12-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20181228_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storages',
            old_name='transfer_builder',
            new_name='transfer',
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_state',
            field=models.IntegerField(choices=[(1, '未入库'), (2, '已入库'), (3, '已出库'), (4, '已借出'), (5, '已注销')], default=1, verbose_name='_权证状态'),
        ),
    ]
