# Generated by Django 2.1.3 on 2018-12-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20181217_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grounds',
            old_name='application',
            new_name='ground_app',
        ),
        migrations.RenameField(
            model_name='grounds',
            old_name='area_structure',
            new_name='ground_area',
        ),
    ]
