# Generated by Django 2.1.3 on 2018-12-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_chattel_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_unit', models.CharField(max_length=64, verbose_name='应收单位名称')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_receiveable', to='A_dbms.Receivable', verbose_name='应收账款')),
            ],
        ),
    ]
