# Generated by Django 2.1.3 on 2019-01-05 12:18

import A_dbms.models.m_appraisal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190105_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingorder',
            name='summary',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_appraisal.limit_lending_choices, on_delete=django.db.models.deletion.PROTECT, related_name='lending_summary', to='A_dbms.Articles', verbose_name='项目纪要'),
        ),
    ]
