# Generated by Django 2.1.3 on 2019-02-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190226_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='auction_state',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.IntegerField(choices=[(1, '日常跟踪'), (3, '拍卖评估'), (5, '拍卖挂网'), (11, '拍卖成交'), (21, '拍卖流拍'), (31, '执行回转'), (99, '注销')], default=1, verbose_name='查询类型'),
        ),
    ]
