# Generated by Django 2.1.3 on 2018-12-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20181225_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customes',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custome_district', to='A_dbms.Districtes', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='idustry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custome_idustry', to='A_dbms.Industries', verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='lendingorder',
            name='order',
            field=models.IntegerField(choices=[(1, '第一次'), (2, '第二次'), (3, '第三次'), (4, '第四次')], default=1, unique=True, verbose_name='发放次序'),
        ),
        migrations.AlterField(
            model_name='lendingsures',
            name='sure_typ',
            field=models.IntegerField(choices=[(1, '企业保证'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '设备抵押'), (14, '存货抵押'), (15, '车辆抵押'), (21, '房产顺位'), (22, '土地顺位'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (41, '合格证监管'), (42, '房产监管'), (43, '土地监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='担保类型'),
        ),
    ]
