# Generated by Django 2.1.3 on 2019-01-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190103_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattel',
            old_name='owner',
            new_name='chattel_owner',
        ),
    ]
