# Generated by Django 2.1.3 on 2019-07-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190715_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingorder',
            name='lending_state',
            field=models.IntegerField(choices=[(3, '待上会'), (4, '已上会'), (5, '已签批'), (51, '已放款'), (52, '已放完'), (55, '已解保'), (61, '待变更'), (99, '已注销')], default=3, verbose_name='_次序状态'),
        ),
    ]
