# Generated by Django 2.1.3 on 2019-04-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190411_1628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('ownership_num', 'warrant', 'owner')},
        ),
    ]
