# Generated by Django 2.1.4 on 2018-12-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20181207_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': '项目-反馈'},
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='credit_model',
            field=models.IntegerField(choices=[(1, '流贷'), (2, '承兑'), (3, '保函'), (4, '综合')], default=1, verbose_name='授信类型'),
        ),
    ]
