# Generated by Django 2.1.7 on 2019-10-23 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_process_typ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-ind'], 'verbose_name_plural': '项目-产品'},
        ),
        migrations.AddField(
            model_name='product',
            name='ind',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_name',
            field=models.IntegerField(choices=[(1, '委托保证合同'), (11, '最高额委托保证合同'), (21, '委托出具分离式保函合同'), (22, '开立保函合同'), (31, '借款合同'), (32, '最高额借款合同'), (41, '委托贷款合同')], verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_typ',
            field=models.IntegerField(choices=[(1, 'D-单笔'), (2, 'D-最高额'), (4, 'D-委贷'), (21, 'D-分离式保函'), (22, 'D-公司保函'), (23, 'D-银行保函'), (41, 'D-单笔(公证)'), (42, 'D-最高额(公证)'), (51, 'X-小贷单笔'), (52, 'X-小贷最高额')], verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='chattel_typ',
            field=models.IntegerField(choices=[(1, '存货'), (11, '机器设备'), (21, '医疗设备'), (99, '动产')], default=1, verbose_name='动产种类'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_name',
            field=models.IntegerField(blank=True, choices=[(1, '保证反担保合同'), (2, '不可撤销的反担保函'), (3, '抵押反担保合同'), (4, '应收账款质押反担保合同'), (5, '股权质押反担保合同'), (6, '质押反担保合同'), (9, '预售合同'), (21, '最高额保证反担保合同'), (23, '最高额抵押反担保合同'), (24, '最高额应收账款质押反担保合同'), (25, '最高额股权质押反担保合同'), (26, '最高额质押反担保合同'), (41, '保证合同'), (43, '抵押合同'), (44, '应收账款质押合同'), (45, '股权质押合同'), (46, '质押合同'), (59, '举办者权益转让协议'), (61, '最高额保证合同'), (63, '最高额抵押合同'), (64, '最高额应收账款质押合同'), (65, '最高额股权质押合同'), (66, '最高额质押合同')], null=True, verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (12, '商业服务'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (47, '营业房'), (48, '研发中心'), (49, '研发楼'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (54, '倒班房及食堂'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (64, '机动车库'), (64, '机动车停车库'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (74, '连廊'), (75, '自行车库'), (76, '生产用房'), (77, '库房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (12, '商业服务'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (47, '营业房'), (48, '研发中心'), (49, '研发楼'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (54, '倒班房及食堂'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (64, '机动车库'), (64, '机动车停车库'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (74, '连廊'), (75, '自行车库'), (76, '生产用房'), (77, '库房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 10, 23), verbose_name='补调日期'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_typ',
            field=models.IntegerField(choices=[(1, '流贷'), (11, '承兑'), (21, '保函'), (31, '委贷'), (41, '小贷综合'), (52, '房抵贷'), (53, '担保贷')], verbose_name='放款种类'),
        ),
    ]
