# Generated by Django 2.1.3 on 2019-02-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0005_auto_20190202_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperators',
            name='up_scale',
            field=models.FloatField(default=0, verbose_name='最高额上浮比例'),
        ),
    ]
