# Generated by Django 2.1.7 on 2020-02-06 08:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20200203_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_name', models.CharField(max_length=64, verbose_name='商标名称')),
                ('reg_num', models.CharField(max_length=64, unique=True, verbose_name='申请/注册号')),
                ('patent_ty', models.IntegerField(verbose_name='国际分类')),
                ('patentor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('other', models.OneToOneField(limit_choices_to={'other_typ': 41}, on_delete=django.db.models.deletion.CASCADE, related_name='patent_other', to='A_dbms.Others', verbose_name='权证')),
                ('patentor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='patentor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '权证-其他-商标',
                'db_table': 'dbms_patent',
            },
        ),
    ]
