# Generated by Django 2.1.3 on 2018-12-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20181228_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storages',
            name='storage_builder',
        ),
        migrations.AddField(
            model_name='storages',
            name='conservator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='conservator_employee', to=settings.AUTH_USER_MODEL, verbose_name='权证管理岗'),
            preserve_default=False,
        ),
    ]
