# Generated by Django 2.1.3 on 2019-07-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20190715_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockes',
            name='remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='lendingorder',
            name='lending_state',
            field=models.IntegerField(choices=[(4, '已上会'), (5, '已签批'), (51, '已放款'), (52, '已放完'), (55, '已解保'), (61, '待变更'), (99, '已注销')], default=4, verbose_name='_次序状态'),
        ),
    ]
