# Generated by Django 2.1.3 on 2019-02-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_cooperators_up_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatories',
            name='dun_state',
            field=models.IntegerField(choices=[(1, '起诉'), (11, '判决'), (21, '执行'), (31, '和解'), (41, '终止执行'), (91, '结案')], default=1, verbose_name='追偿状态'),
        ),
        migrations.AlterField(
            model_name='compensatories',
            name='retrieve_amount',
            field=models.FloatField(verbose_name='追偿总额'),
        ),
    ]
