# Generated by Django 2.1.3 on 2019-04-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20190411_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrants',
            name='evaluate_state',
            field=models.IntegerField(choices=[(0, '待评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本'), (41, '拍卖评估'), (99, '无需评估')], default=0, verbose_name='评估方式'),
        ),
    ]
