# Generated by Django 2.1.3 on 2018-12-31 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_receiveextend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_typ', models.IntegerField(choices=[(1, '银行承兑汇票'), (2, '商业承兑汇票'), (2, '支票')], default=1, verbose_name='票据种类')),
                ('detail', models.TextField(verbose_name='汇票描述')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_custome', to='A_dbms.Customes', verbose_name='所有权人')),
                ('warrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_warrant', to='A_dbms.Warrants', verbose_name='权证')),
            ],
            options={
                'verbose_name_plural': '权证-应收票据',
                'db_table': 'dbms_draft',
            },
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name_plural': '放款-放款通知'},
        ),
        migrations.AlterModelOptions(
            name='pigeonholes',
            options={'verbose_name_plural': '放款-归档'},
        ),
        migrations.AlterModelOptions(
            name='provides',
            options={'verbose_name_plural': '放款'},
        ),
        migrations.AddField(
            model_name='notify',
            name='notify_date',
            field=models.DateField(default=datetime.date.today, verbose_name='日期'),
        ),
    ]
