# Generated by Django 2.1.3 on 2018-11-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20181119_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'permissions': (('dbms_article_list', '访问项目列表'), ('dbms_article_list_all', '访问所有项目列表'), ('dbms_article_add_view', '访问项目添加页'), ('dbms_article_add_change', '添加项目'), ('crm_table_list', '可以查看kingadmin每张表里所有的数据'), ('crm_table_list_view', '可以访问kingadmin表里每条数据的修改页'), ('crm_table_list_change', '可以对kingadmin表里的每条数据进行修改'), ('crm_table_obj_add_view', '可以访问kingadmin每张表的数据增加页'), ('crm_table_obj_add', '可以对kingadmin每张表进行数据添加')), 'verbose_name_plural': '内部-员工'},
        ),
    ]
