# Generated by Django 2.1.4 on 2018-12-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20181208_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='concrete',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='意见详情'),
        ),
    ]
