# Generated by Django 2.1.3 on 2019-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20190226_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrants',
            name='inquiry_remark',
        ),
        migrations.AddField(
            model_name='warrants',
            name='inquiry_detail',
            field=models.TextField(blank=True, null=True, verbose_name='查询情况'),
        ),
    ]
