# Generated by Django 2.1.3 on 2019-02-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20190223_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seal',
            name='sequest_term',
        ),
        migrations.AddField(
            model_name='seal',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='查封到期日'),
        ),
    ]
