# Generated by Django 2.1.3 on 2019-01-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0006_auto_20190103_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattel',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 51}, on_delete=django.db.models.deletion.CASCADE, related_name='chattel_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draft_typ',
            field=models.IntegerField(choices=[(1, '银行承兑汇票'), (2, '商业承兑汇票'), (3, '支票')], default=1, verbose_name='票据种类'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 31}, on_delete=django.db.models.deletion.CASCADE, related_name='draft_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 99}, on_delete=django.db.models.deletion.CASCADE, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 11}, on_delete=django.db.models.deletion.CASCADE, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 21}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 41}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '土地'), (11, '应收'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '其他'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
    ]
