# Generated by Django 2.1.3 on 2018-12-26 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20181226_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingcustoms',
            name='sure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_sure', to='A_dbms.LendingSures', verbose_name='反担保措施'),
        ),
    ]
