# Generated by Django 2.1.3 on 2019-02-26 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20190226_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_term',
        ),
        migrations.AddField(
            model_name='agent',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='到期日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.IntegerField(choices=[(1, '还款承诺'), (3, '委托代理'), (5, '起诉'), (11, '受理'), (15, '财产保全'), (21, '和解'), (25, '调解'), (31, '判决'), (32, '上诉'), (41, '执行'), (43, '执行异议'), (45, '执行中止'), (47, '终止执行'), (51, '资料递交'), (91, '公告'), (99, '其他')], verbose_name='阶段'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='auction_state',
            field=models.IntegerField(choices=[(1, '正常'), (2, '冻结'), (3, '评估'), (5, '挂网'), (11, '成交'), (21, '流拍'), (31, '回转'), (99, '注销')], default=1, verbose_name='_拍卖状态'),
        ),
    ]
