# Generated by Django 2.1.3 on 2019-01-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20181231_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisals',
            name='review_year',
            field=models.IntegerField(default=2019, verbose_name='评审年份'),
        ),
    ]
