# Generated by Django 2.1.3 on 2018-11-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20181120_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32, unique=True, verbose_name='审保会编号')),
                ('review_model', models.IntegerField(choices=[(1, '内审'), (2, '外审')], verbose_name='评审类型')),
                ('review_order', models.IntegerField(verbose_name='评审次序')),
                ('review_date', models.DateField(default=datetime.date.today, verbose_name='评审日期')),
            ],
            options={
                'db_table': 'dbms_appraisals',
                'verbose_name_plural': '评审-审保会',
            },
        ),
        migrations.RemoveField(
            model_name='articles',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='review_model',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='review_order',
        ),
        migrations.AddField(
            model_name='appraisals',
            name='article',
            field=models.ManyToManyField(related_name='appraisal_article', to='A_dbms.Articles', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='appraisals',
            name='expert',
            field=models.ManyToManyField(related_name='appraisal_expert', to='A_dbms.Experts', verbose_name='评审'),
        ),
    ]
