# Generated by Django 2.1.3 on 2019-01-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20190103_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_num', models.CharField(max_length=64, verbose_name='票据编号')),
                ('draft_drawer', models.CharField(max_length=64, verbose_name='出票人')),
                ('draft_acceptor', models.CharField(max_length=64, verbose_name='承兑人')),
                ('issue_date', models.DateField(verbose_name='出票日期')),
                ('due_date', models.DateField(verbose_name='到期日')),
            ],
            options={
                'verbose_name_plural': '权证-票据明细',
                'db_table': 'dbms_draftextend',
            },
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='rraft_detail',
            new_name='draft_detail',
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='owner',
            new_name='draft_owner',
        ),
        migrations.AddField(
            model_name='draftextend',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_receiveable', to='A_dbms.Draft', verbose_name='票据'),
        ),
    ]
