# Generated by Django 2.1.3 on 2019-02-11 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20190211_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatories',
            name='compensatory_date',
            field=models.DateField(default=datetime.date.today, verbose_name='代偿日期'),
        ),
    ]
