# Generated by Django 2.1.3 on 2019-04-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20190412_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'ordering': ['name'], 'verbose_name_plural': '外部-放款银行'},
        ),
        migrations.AlterModelOptions(
            name='experts',
            options={'ordering': ['ordery'], 'verbose_name_plural': '外部-评审专家'},
        ),
        migrations.AlterField(
            model_name='storages',
            name='storage_typ',
            field=models.IntegerField(choices=[(1, '入库'), (2, '续抵出库'), (6, '无需入库'), (11, '借出'), (12, '归还'), (31, '解保出库')], default=1, verbose_name='出入库'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='evaluate_state',
            field=models.IntegerField(choices=[(0, '待评估'), (5, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本'), (41, '拍卖评估'), (99, '无需评估')], default=0, verbose_name='评估方式'),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together={('warrant', 'owner')},
        ),
    ]
