# Generated by Django 2.1.3 on 2019-07-18 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0007_auto_20190715_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='add_amount',
            field=models.IntegerField(default=0, verbose_name='补调'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='review_amount',
            field=models.IntegerField(default=0, verbose_name='保后'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 7, 18), verbose_name='补调日期'),
        ),
    ]
