# Generated by Django 2.1.3 on 2019-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20190223_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seal',
            name='inquiry_date',
        ),
        migrations.AddField(
            model_name='warrants',
            name='inquiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='最近查询日'),
        ),
        migrations.AddField(
            model_name='warrants',
            name='inquiry_remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='查询情况'),
        ),
    ]
