# Generated by Django 2.1.3 on 2019-02-12 01:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20190211_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatories',
            name='compensator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compensator_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compensatories',
            name='compensator_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agree_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
