# Generated by Django 2.1.7 on 2020-03-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20200211_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provides',
            name='obj_typ',
            field=models.IntegerField(choices=[(1, '农户贷款'), (11, '关联企业或个体工商户贷款'), (15, '个人消费贷款'), (21, '农村企业贷款'), (23, '城市-小微企业'), (25, '城市-其他企业'), (99, '其他')], default=99, verbose_name='贷款对象分类'),
        ),
    ]
