# Generated by Django 2.1.3 on 2019-01-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20190103_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
    ]
