# Generated by Django 2.1.4 on 2018-12-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20181208_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='sign_detail',
            field=models.TextField(blank=True, null=True, verbose_name='签批详情'),
        ),
        migrations.AddField(
            model_name='articles',
            name='sign_type',
            field=models.IntegerField(choices=[(1, '同意'), (2, '不同意')], default=1, verbose_name='签批意见'),
        ),
    ]
