# Generated by Django 2.1.3 on 2019-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20190718_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='custom_typ',
            field=models.IntegerField(choices=[(1, '企业'), (2, '个人')], default=1, verbose_name='新增标志'),
        ),
    ]
