# Generated by Django 2.1.3 on 2018-12-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20181226_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingcustoms',
            name='custome',
            field=models.ManyToManyField(db_constraint=False, related_name='lending_custome', to='A_dbms.Customes', verbose_name='反担保人'),
        ),
        migrations.AlterField(
            model_name='lendingwarrants',
            name='warrant',
            field=models.ManyToManyField(db_constraint=False, related_name='lending_warrant', to='A_dbms.Warrants', verbose_name='抵质押物'),
        ),
    ]
