# Generated by Django 2.1.3 on 2019-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0008_auto_20190226_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='dun',
            name='custom',
            field=models.ManyToManyField(blank=True, null=True, related_name='dun_custom', to='A_dbms.Customes', verbose_name='被告人'),
        ),
    ]
