# Generated by Django 2.1.3 on 2019-04-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_auto_20190415_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-build_date', '-id'], 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='customes',
            options={'ordering': ['genre', 'name'], 'verbose_name_plural': '客户'},
        ),
        migrations.AlterModelOptions(
            name='districtes',
            options={'ordering': ['name'], 'verbose_name_plural': '客户-区域'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['name'], 'permissions': [('dbms_article_all', '访问项目列表'), ('dbms_article', '访问所有项目列表'), ('article_scan_all', '访问项目添加页'), ('article_scan_agree', '添加项目')], 'verbose_name_plural': '内部-员工'},
        ),
        migrations.AlterModelOptions(
            name='industries',
            options={'ordering': ['code'], 'verbose_name_plural': '客户-行业'},
        ),
        migrations.AlterModelOptions(
            name='lendingwarrants',
            options={'ordering': ['lending_w_date'], 'verbose_name_plural': '反担保-抵质押'},
        ),
        migrations.AlterModelOptions(
            name='seal',
            options={'ordering': ['-seal_date'], 'verbose_name_plural': '追偿-查封现状'},
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='evaluate_state',
            field=models.IntegerField(choices=[(0, '待评估'), (1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本'), (41, '拍卖评估'), (99, '无需评估')], default=1, verbose_name='评估方式'),
        ),
        migrations.AlterField(
            model_name='pigeonholes',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档'), (99, '无需归档')], default=1, verbose_name='归档状态'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档'), (99, '无需归档')], default=1, verbose_name='_归档状态'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='sealup_type',
            field=models.IntegerField(choices=[(1, '查询跟踪'), (3, '诉前保全'), (5, '首次首封'), (11, '首次轮封'), (21, '续查封'), (51, '解除查封'), (99, '注销')], default=1, verbose_name='查封类型'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='evaluate_state',
            field=models.IntegerField(choices=[(0, '待评估'), (1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本'), (41, '拍卖评估'), (99, '无需评估')], default=0, verbose_name='评估方式'),
        ),
        migrations.AlterUniqueTogether(
            name='receiveextend',
            unique_together={('receivable', 'receive_unit')},
        ),
    ]
