# Generated by Django 2.1.3 on 2019-02-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_dun_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='custom_state',
            field=models.IntegerField(choices=[(1, '正常'), (99, '注销')], default=1, verbose_name='_风险分类'),
        ),
    ]
