# Generated by Django 2.1.3 on 2019-01-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_auto_20190101_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensatories',
            name='compensatory_implement',
        ),
        migrations.AddField(
            model_name='compensatories',
            name='dun_state',
            field=models.IntegerField(choices=[(1, '起诉'), (2, '判决'), (3, '执行'), (4, '和解结案'), (5, '终止执行')], default=1, verbose_name='追偿状态'),
        ),
    ]
