# Generated by Django 2.1.3 on 2019-02-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_auto_20190223_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='seal_state',
            field=models.IntegerField(choices=[(1, '未查封'), (11, '已查封'), (71, '已解封'), (99, '注销')], default=1, verbose_name='查封状态'),
        ),
    ]
