# Generated by Django 2.1.3 on 2018-11-23 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_auto_20181123_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summaries',
            options={'verbose_name_plural': '评审-纪要'},
        ),
        migrations.AlterModelTable(
            name='summaries',
            table='dbms_summaries',
        ),
    ]
