# Generated by Django 2.1.3 on 2019-01-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_auto_20190103_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receivable',
            old_name='owner',
            new_name='receive_owner',
        ),
        migrations.AlterField(
            model_name='countersassure',
            name='counter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assure_counter', to='A_dbms.Counters', verbose_name='反担保合同'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '土地'), (11, '应收'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '动产'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
    ]
