# Generated by Django 2.1.3 on 2019-07-29 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_customes_custom_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='lately_provide',
            field=models.DateField(blank=True, null=True, verbose_name='最近放款'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='custom_typ',
            field=models.IntegerField(choices=[(1, '--'), (11, '新增'), (21, '存量'), (31, '存量新增')], default=1, verbose_name='新增标志'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 7, 29), verbose_name='补调日期'),
        ),
    ]
