# Generated by Django 2.1.7 on 2020-03-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0009_auto_20200313_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='g_value',
            field=models.FloatField(default=0, verbose_name='反担保价值'),
        ),
    ]
