# Generated by Django 2.1.3 on 2019-02-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_auto_20190212_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatories',
            name='default_interest',
            field=models.FloatField(default=0, verbose_name='代偿罚息'),
        ),
        migrations.AlterField(
            model_name='compensatories',
            name='dun_state',
            field=models.IntegerField(choices=[(1, '已代偿'), (11, '已起诉'), (21, '已判决'), (31, '已和解'), (41, '执行中'), (91, '结案')], default=1, verbose_name='追偿状态'),
        ),
    ]
