# Generated by Django 2.1.3 on 2019-02-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_customes_custom_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='custom_dun_state',
            field=models.IntegerField(choices=[(1, '正常'), (11, '被告'), (99, '注销')], default=1, verbose_name='_风险分类'),
        ),
    ]
