# Generated by Django 2.1.3 on 2019-02-23 10:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_auto_20190223_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_date', models.DateField(verbose_name='查询日期')),
                ('inquiry_detail', models.TextField(blank=True, null=True, verbose_name='查询情况')),
                ('inquiryor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('inquiryor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiryor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'dbms_inquiry',
                'verbose_name_plural': '追偿-查询情况',
            },
        ),
        migrations.CreateModel(
            name='Sealup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sealup_type', models.IntegerField(choices=[(1, '首次首封'), (11, '首次轮封'), (21, '续查封'), (51, '解除查封'), (99, '注销')], default=1, verbose_name='查封类型')),
                ('sealup_date', models.DateField(verbose_name='查封日期')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('sealup_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('sealupor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'db_table': 'dbms_sealup',
                'verbose_name_plural': '追偿-查封情况',
            },
        ),
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '起诉'), (11, '判决'), (21, '执行'), (31, '和解结案'), (41, '终止执行'), (99, '注销')], default=1, verbose_name='追偿状态'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='seal_state',
            field=models.IntegerField(choices=[(1, '未查封'), (11, '首查封'), (71, '轮候查封'), (99, '注销')], default=1, verbose_name='查封状态'),
        ),
        migrations.AddField(
            model_name='sealup',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealup_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AddField(
            model_name='sealup',
            name='sealupor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealup_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
    ]
