# Generated by Django 2.1.3 on 2019-01-04 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_auto_20190103_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='notify_provide_amount',
            field=models.FloatField(default=0, verbose_name='放款金额'),
        ),
        migrations.AddField(
            model_name='notify',
            name='notifyor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifyor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menus',
            name='name',
            field=models.CharField(max_length=64, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='ordery',
            field=models.IntegerField(verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url_name',
            field=models.CharField(max_length=128, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='credit_model',
            field=models.IntegerField(choices=[(1, '流动资金贷款担保'), (2, '银行承兑汇票担保'), (3, '保函担保'), (4, '综合授信额度担保（含流贷、银承、保函）')], default=1, verbose_name='授信类型'),
        ),
    ]
