# Generated by Django 2.1.3 on 2019-04-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_auto_20190419_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockes',
            name='registe',
            field=models.FloatField(default=0, verbose_name='注册资本（万）'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='share',
            field=models.FloatField(default=0, verbose_name='实缴资本（万）'),
        ),
    ]
