# Generated by Django 2.1.3 on 2019-07-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_auto_20190729_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customes',
            old_name='lately_provide',
            new_name='provide_date',
        ),
    ]
