# Generated by Django 2.1.7 on 2020-03-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_customes_g_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='investigation_fee',
            field=models.FloatField(default=0, verbose_name='调查费率(%)'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='supplementary',
            field=models.TextField(blank=True, null=True, verbose_name='补充协议'),
        ),
        migrations.AddField(
            model_name='customes',
            name='g_radio',
            field=models.FloatField(default=0, verbose_name='覆盖率(%)'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_rate',
            field=models.TextField(verbose_name='保费率/利率'),
        ),
    ]
