# Generated by Django 2.1.3 on 2019-01-06 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0010_auto_20190106_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges',
            name='charge_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='charge_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='pigeonholor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pigeonholor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='repayments',
            name='repaymentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='repaymentor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='article_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='notify',
            name='notifyor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='notifyor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='providor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='providor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
    ]
