# Generated by Django 2.1.3 on 2019-08-02 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20190729_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='day_space',
            field=models.IntegerField(default=0, verbose_name='间隔（日）'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_name',
            field=models.IntegerField(choices=[(1, '委托保证合同'), (11, '最高额委托保证合同'), (21, '委托出具分离式保函合同'), (22, '开立保函合同'), (31, '借款合同'), (41, '委托贷款合同')], verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_typ',
            field=models.IntegerField(choices=[(1, '单笔'), (2, '最高额'), (4, '委贷'), (7, '小贷'), (21, '分离式保函'), (22, '公司保函'), (23, '银行保函'), (41, '单笔(公证)'), (42, '最高额(公证)'), (47, '小贷(公证)')], verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 8, 2), verbose_name='补调日期'),
        ),
    ]
