# Generated by Django 2.1.3 on 2019-02-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20190212_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatories',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compensatory_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
    ]
