# Generated by Django 2.1.7 on 2020-03-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20200316_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='v_radio',
            field=models.FloatField(default=0, verbose_name='在保覆盖率(%)'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='g_radio',
            field=models.FloatField(default=0, verbose_name='授信覆盖率(%)'),
        ),
    ]
