# Generated by Django 2.1.3 on 2019-01-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20190104_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='notify_provide_amount',
            new_name='notify_provide_sum',
        ),
        migrations.RemoveField(
            model_name='agrees',
            name='agree_balance',
        ),
        migrations.AddField(
            model_name='agrees',
            name='agree_notify_sum',
            field=models.FloatField(default=0, verbose_name='_通知金额'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='agree_provide_sum',
            field=models.FloatField(default=0, verbose_name='_放款金额'),
        ),
    ]
