# Generated by Django 2.1.3 on 2019-02-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_customes_custom_dun_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_state',
            field=models.IntegerField(choices=[(1, '证据及财产线索'), (11, '诉前资料'), (21, '一审资料'), (31, '上诉及再审'), (41, '案外之诉'), (51, '执行资料'), (99, '其他')], default=1, verbose_name='资料类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '诉前'), (3, '起诉'), (11, '判决'), (21, '执行'), (31, '和解'), (41, '中止执行'), (51, '终本执行'), (61, '终止执行'), (99, '注销')], default=1, verbose_name='追偿状态'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.IntegerField(choices=[(1, '代理律师'), (11, '审判法官'), (21, '执行法官'), (31, '评估人员'), (41, '代理员工'), (51, '助拍人员'), (51, '竞拍人员'), (99, '其他人员')], verbose_name='人员类型'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.IntegerField(choices=[(1, '还款承诺'), (3, '委托代理'), (5, '起诉'), (11, '受理'), (15, '财产保全'), (21, '和解'), (25, '调解'), (31, '判决'), (32, '上诉'), (41, '执行'), (43, '执行异议'), (45, '执行中止'), (47, '终止执行'), (51, '资料递交'), (91, '公告'), (99, '其他')], verbose_name='资料类型'),
        ),
    ]
