# Generated by Django 2.1.3 on 2019-04-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20190422_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='车辆品牌'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='chattel_typ',
            field=models.IntegerField(choices=[(1, '存货'), (11, '机器设备'), (99, '其他')], default=1, verbose_name='动产种类'),
        ),
        migrations.AlterField(
            model_name='draftextend',
            name='draft_typ',
            field=models.IntegerField(choices=[(1, '电子银行承兑汇票'), (2, '银行承兑汇票'), (11, '电子商业承兑汇票'), (12, '商业承兑汇票'), (21, '支票')], default=1, verbose_name='票据种类'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='registe',
            field=models.FloatField(default=0, verbose_name='认缴资本（万）'),
        ),
    ]
