# Generated by Django 2.1.3 on 2019-01-06 05:03

import A_dbms.models.m_appraisal
import A_dbms.models.m_warrant
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20190106_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='签批日期'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '已落实，未放款'), (41, '已落实，放款'), (42, '未落实，放款'), (51, '待变更'), (61, '已解保'), (99, '已作废')], default=11, verbose_name='_合同状态'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='agree',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_warrant.limit_agree_choices, on_delete=django.db.models.deletion.PROTECT, related_name='ypothec_agree', to='A_dbms.Agrees', verbose_name='委托合同'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='summary',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_appraisal.limit_article_choices, on_delete=django.db.models.deletion.PROTECT, related_name='single_quota_summary', to='A_dbms.Articles', verbose_name='纪要'),
        ),
    ]
