# Generated by Django 2.1.3 on 2019-02-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20190223_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealup_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='sealup_type',
            field=models.IntegerField(choices=[(1, '诉前保全'), (5, '首次首封'), (11, '首次轮封'), (21, '续查封'), (51, '解除查封'), (99, '注销')], default=1, verbose_name='查封类型'),
        ),
    ]
