# Generated by Django 2.1.7 on 2019-11-14 06:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0011_auto_20191112_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorities',
            options={'ordering': ['url_name'], 'verbose_name_plural': '内部-权限'},
        ),
        migrations.AlterField(
            model_name='customes',
            name='controler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controler_employee', to=settings.AUTH_USER_MODEL, verbose_name='风控专员'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='custom_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custom_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='custom_state',
            field=models.IntegerField(choices=[(11, '担保客户'), (21, '反担保客户'), (31, '小贷客户'), (99, '注销客户')], default=11, verbose_name='客户状态'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='managementor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='manage_employee', to=settings.AUTH_USER_MODEL, verbose_name='管护经理'),
        ),
        migrations.AlterField(
            model_name='customesc',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custome_district', to='A_dbms.Districtes', verbose_name='所属区域'),
        ),
        migrations.AlterField(
            model_name='customesc',
            name='idustry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custome_idustry', to='A_dbms.Industries', verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 11, 14), verbose_name='补调日期'),
        ),
    ]
