# Generated by Django 2.1.3 on 2019-08-05 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0012_auto_20190802_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customes',
            name='lately_date',
            field=models.DateField(blank=True, null=True, verbose_name='最近更新'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 8, 5), verbose_name='补调日期'),
        ),
    ]
