# Generated by Django 2.1.7 on 2020-03-31 23:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0012_auto_20200318_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_pried', models.FloatField(default=0, verbose_name='已收当期本金')),
                ('ex_inted', models.FloatField(default=0, verbose_name='已收当期利息')),
                ('ex_pened', models.FloatField(default=0, verbose_name='已收当期违约金')),
                ('ex_tamted', models.FloatField(default=0, verbose_name='已收当期总额')),
                ('ex_track_date', models.DateField(verbose_name='跟踪日期')),
                ('ex_condition', models.TextField(blank=True, null=True, verbose_name='跟踪情况')),
                ('ex_date', models.DateField(default=datetime.date.today, verbose_name='_创建日期')),
                ('ex_trackor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ex_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者')),
            ],
            options={
                'verbose_name_plural': '放款-跟踪-EX',
                'db_table': 'dbms_trackex',
                'ordering': ['-ex_track_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='repayments',
            options={'ordering': ['-repaymentdate'], 'verbose_name_plural': '项目-还款'},
        ),
        migrations.AddField(
            model_name='repayments',
            name='repayment_amt',
            field=models.FloatField(default=0, verbose_name='当期还款总额额'),
        ),
        migrations.AddField(
            model_name='repayments',
            name='repayment_int',
            field=models.FloatField(default=0, verbose_name='当期还款利息额'),
        ),
        migrations.AddField(
            model_name='repayments',
            name='repayment_pen',
            field=models.FloatField(default=0, verbose_name='当期还款违约金额'),
        ),
        migrations.AddField(
            model_name='track',
            name='ddd_pro',
            field=models.DateField(blank=True, null=True, verbose_name='起始日期'),
        ),
        migrations.AddField(
            model_name='track',
            name='prin',
            field=models.FloatField(default=0, verbose_name='剩余本金'),
        ),
        migrations.AddField(
            model_name='track',
            name='pro_aft_dif',
            field=models.IntegerField(default=0, verbose_name='计息天数'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_amt',
            field=models.FloatField(default=0, verbose_name='应收当期总额'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_amted',
            field=models.FloatField(default=0, verbose_name='已收当期总额'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_int',
            field=models.FloatField(default=0, verbose_name='应收当期利息'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_int_j',
            field=models.FloatField(default=0, verbose_name='计息本金'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_inted',
            field=models.FloatField(default=0, verbose_name='已收当期利息'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_pen',
            field=models.FloatField(default=0, verbose_name='应收当期违约金'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_pened',
            field=models.FloatField(default=0, verbose_name='已收当期违约金'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_pri',
            field=models.FloatField(default=0, verbose_name='应收当期本金'),
        ),
        migrations.AddField(
            model_name='track',
            name='term_pried',
            field=models.FloatField(default=0, verbose_name='已收当期本金'),
        ),
        migrations.AddField(
            model_name='track',
            name='total_int',
            field=models.FloatField(default=0, verbose_name='利息累计'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='petty_loan',
            field=models.FloatField(default=0, verbose_name='小贷'),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='repayment_money',
            field=models.FloatField(default=0, verbose_name='当期还款本金额'),
        ),
        migrations.AlterField(
            model_name='track',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_typ',
            field=models.IntegerField(choices=[(11, '日常跟踪'), (21, '分期还本'), (25, '等额本息'), (31, '按月付息')], default=11, verbose_name='跟踪类型'),
        ),
        migrations.AddField(
            model_name='trackex',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ex_track', to='A_dbms.Track', verbose_name='跟踪'),
        ),
    ]
