# Generated by Django 2.1.3 on 2019-04-23 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0012_auto_20190424_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(default=1, max_length=64, verbose_name='车辆品牌'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_remark',
            field=models.CharField(default=1, max_length=64, verbose_name='备注'),
        ),
    ]
