# Generated by Django 2.1.3 on 2019-02-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0012_auto_20190227_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='stage_state',
        ),
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '诉前'), (3, '起诉'), (11, '判决'), (13, '二审'), (15, '再审'), (17, '再审'), (21, '执行'), (31, '和解'), (41, '中止执行'), (51, '终本执行'), (61, '终止执行'), (99, '注销')], default=1, verbose_name='追偿状态'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.IntegerField(choices=[(1, '证据及财产线索资料'), (11, '诉前资料'), (21, '一审资料'), (31, '上诉及再审'), (41, '案外之诉'), (51, '执行资料'), (99, '其他')], verbose_name='资料类型'),
        ),
    ]
