# Generated by Django 2.1.3 on 2019-01-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0012_auto_20190104_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lendingorder',
            old_name='amount',
            new_name='lending_provide_sum',
        ),
    ]
