# Generated by Django 2.1.3 on 2019-01-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0012_auto_20190106_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='counter_state',
            field=models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '已注销')], default=11, verbose_name='_签订情况'),
        ),
    ]
