# Generated by Django 2.1.3 on 2019-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20190227_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_state',
            field=models.IntegerField(choices=[(1, '原件'), (11, '复印件')], default=1, verbose_name='原件或复印件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='索引号'),
        ),
    ]
