# Generated by Django 2.1.3 on 2019-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20190104_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_provide_sum',
            field=models.FloatField(default=0, verbose_name='_放款金额'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='accept_loan',
            field=models.FloatField(default=0, verbose_name='_承兑余额'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='back_loan',
            field=models.FloatField(default=0, verbose_name='_保函余额'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='credit_amount',
            field=models.FloatField(default=0, verbose_name='授信总额'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='flow_loan',
            field=models.FloatField(default=0, verbose_name='_流贷余额'),
        ),
        migrations.AlterField(
            model_name='lendingorder',
            name='lending_provide_sum',
            field=models.FloatField(default=0, verbose_name='_放款金额'),
        ),
    ]
