# Generated by Django 2.1.3 on 2019-02-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20190212_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_notify_sum',
            field=models.FloatField(default=0, verbose_name='_通知金额'),
        ),
    ]
