# Generated by Django 2.1.3 on 2018-11-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20181123_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarynum',
            options={'verbose_name_plural': '评审-额度'},
        ),
    ]
