# Generated by Django 2.1.3 on 2019-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20190424_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(max_length=64, verbose_name='品牌型号'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
    ]
