# Generated by Django 2.1.7 on 2020-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20200401_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_state',
            field=models.IntegerField(choices=[(11, '未结清'), (21, '已结清')], default=11, verbose_name='计划状态'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_typ',
            field=models.IntegerField(choices=[(11, '日常计划'), (21, '分期还本'), (25, '等额本息'), (31, '按月付息')], default=11, verbose_name='计划类型'),
        ),
        migrations.AlterField(
            model_name='trackex',
            name='ex_condition',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='trackex',
            name='ex_track_date',
            field=models.DateField(verbose_name='回款日期'),
        ),
    ]
