# Generated by Django 2.1.3 on 2019-01-08 01:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0013_auto_20190108_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(max_length=8, unique=True, verbose_name='简称')),
                ('invested_amount', models.FloatField(verbose_name='投资额')),
                ('shareholding_ratio', models.FloatField(verbose_name='持股比例（%）')),
                ('shareholder_date', models.DateField(default=datetime.date.today, verbose_name='创建时间')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder_custom_c', to='A_dbms.CustomesC', verbose_name='企业客户')),
                ('shareholderor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shareholderor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '客户-股东信息',
                'db_table': 'dbms_shareholders',
            },
        ),
    ]
