# Generated by Django 2.1.3 on 2019-01-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_auto_20190104_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customesc',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custome_district', to='A_dbms.Districtes', verbose_name='所属区域'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customesc',
            name='idustry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custome_idustry', to='A_dbms.Industries', verbose_name='所属行业'),
            preserve_default=False,
        ),
    ]
