# Generated by Django 2.1.7 on 2019-08-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_auto_20190830_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letterguarantee',
            old_name='guarantee_typ',
            new_name='letter_typ',
        ),
    ]
