# Generated by Django 2.1.3 on 2019-02-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_auto_20190227_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgment',
            name='judgment_file',
            field=models.CharField(max_length=64, unique=True, verbose_name='文件编号'),
        ),
    ]
