# Generated by Django 2.1.3 on 2019-01-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_shareholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholders',
            name='shareholder_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='简称'),
        ),
    ]
