# Generated by Django 2.1.3 on 2019-02-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_auto_20190223_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.IntegerField(choices=[(1, '日常跟踪'), (5, '拍卖挂网'), (11, '拍卖成交'), (21, '拍卖流拍'), (31, '执行回转'), (99, '注销')], default=1, verbose_name='查询类型'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealup_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
    ]
