# Generated by Django 2.1.7 on 2020-04-20 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_auto_20200403_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repayments',
            options={'ordering': ['-repayment_date'], 'verbose_name_plural': '项目-还款'},
        ),
        migrations.AddField(
            model_name='dun',
            name='up_date',
            field=models.DateField(default=datetime.date.today, verbose_name='跟新日期'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='credit_model',
            field=models.IntegerField(choices=[(1, '流动资金贷款'), (2, '银行承兑汇票敞口'), (3, '保函'), (4, '综合授信额度（含流贷、银承、保函）'), (31, '委托贷款')], default=1, verbose_name='授信类型'),
        ),
    ]
