# Generated by Django 2.1.3 on 2019-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0014_articles_article_notify_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='amount_limit',
            field=models.FloatField(default=0, verbose_name='放款限额'),
        ),
    ]
