# Generated by Django 2.1.3 on 2019-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_agrees_amount_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='amount_limit',
            field=models.FloatField(verbose_name='放款限额'),
        ),
    ]
