# Generated by Django 2.1.3 on 2019-02-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_auto_20190227_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_custom', to='A_dbms.Customes', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='dun',
            name='compensatory',
            field=models.ManyToManyField(blank=True, null=True, related_name='dun_compensatory', to='A_dbms.Compensatories', verbose_name='代偿'),
        ),
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '诉前'), (3, '起诉'), (11, '判决'), (13, '二审'), (15, '再审'), (21, '执行'), (31, '和解'), (41, '中止执行'), (51, '终本执行'), (61, '终止执行'), (99, '注销')], default=1, verbose_name='追偿状态'),
        ),
    ]
