# Generated by Django 2.1.3 on 2018-11-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_summarynum_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32, unique=True, verbose_name='单项额度')),
                ('credit_model', models.IntegerField(choices=[(1, '流贷'), (2, '承兑'), (3, '保函')], default=1, verbose_name='授信类型')),
                ('credit_amount', models.FloatField(verbose_name='授信额度（元）')),
                ('flow_rate', models.FloatField(verbose_name='费率（%）')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='single_quota_summary', to='A_dbms.Articles', verbose_name='纪要')),
            ],
            options={
                'verbose_name_plural': '评审-额度',
                'db_table': 'dbms_single_quota',
            },
        ),
        migrations.RemoveField(
            model_name='summarynum',
            name='summary',
        ),
        migrations.DeleteModel(
            name='SummaryNum',
        ),
    ]
