# Generated by Django 2.1.7 on 2020-04-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_auto_20200420_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingsures',
            name='sure_typ',
            field=models.IntegerField(choices=[(1, '企业保证'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (14, '在建工程抵押'), (15, '车辆抵押'), (21, '房产顺位抵押'), (22, '土地顺位抵押'), (23, '在建工程顺位抵押'), (24, '动产顺位抵押'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (34, '动产质押'), (39, '其他权利质押'), (42, '房产监管'), (43, '土地监管'), (44, '票据监管'), (47, '动产监管'), (49, '其他监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售'), (59, '其他')], verbose_name='担保类型'),
        ),
    ]
