# Generated by Django 2.1.7 on 2019-09-04 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_auto_20190830_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 9, 4), verbose_name='补调日期'),
        ),
        migrations.AlterField(
            model_name='letterguarantee',
            name='agree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_agree', to='A_dbms.Agrees', verbose_name='委托保证合同'),
        ),
    ]
