# Generated by Django 2.1.3 on 2019-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_auto_20190223_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standing',
            name='standing_date',
        ),
        migrations.AlterField(
            model_name='dun',
            name='warrant',
            field=models.ManyToManyField(blank=True, null=True, related_name='dun_warrant', to='A_dbms.Warrants', verbose_name='资产线索'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='seal_state',
            field=models.IntegerField(choices=[(1, '诉前保全'), (5, '首次首封'), (11, '首次轮封'), (21, '续查封'), (51, '解除查封'), (99, '注销')], verbose_name='查封状态'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealup_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AlterField(
            model_name='standing',
            name='standing_detail',
            field=models.TextField(verbose_name='追偿情况'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='auction_state',
            field=models.IntegerField(choices=[(1, '正常'), (5, '挂网'), (11, '成交'), (21, '流拍'), (31, '回转'), (99, '注销')], default=1, verbose_name='_拍卖状态'),
        ),
    ]
