# Generated by Django 2.1.3 on 2019-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_auto_20190424_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultstate',
            options={'ordering': ['-agree'], 'verbose_name_plural': '合同-决议及声明'},
        ),
        migrations.AddField(
            model_name='resultstate',
            name='result_detail',
            field=models.TextField(blank=True, null=True, verbose_name='决议声明内容'),
        ),
    ]
