# Generated by Django 2.1.3 on 2019-01-04 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0015_auto_20190104_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provides',
            name='provide_balance',
        ),
        migrations.AddField(
            model_name='provides',
            name='providor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='providor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provides',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (2, '暂存风控'), (3, '已归档')], default=1, verbose_name='_归档状态'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_status',
            field=models.IntegerField(choices=[(1, '在保'), (2, '解保'), (3, '代偿')], default=1, verbose_name='_放款状态'),
        ),
    ]
