# Generated by Django 2.1.3 on 2019-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20190227_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensatories',
            name='title',
            field=models.CharField(default='1', max_length=128, verbose_name='标志'),
            preserve_default=False,
        ),
    ]
