# Generated by Django 2.1.3 on 2018-11-26 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20181126_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=32, unique=True, verbose_name='评委意见')),
                ('comment_type', models.IntegerField(choices=[(1, '同意'), (2, '复议'), (3, '不同意')], default=1, verbose_name='授信类型')),
                ('concrete', models.CharField(blank=True, max_length=256, null=True, verbose_name='意见详情')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_summary', to='A_dbms.Articles', verbose_name='纪要')),
            ],
            options={
                'verbose_name_plural': '评审-意见',
                'db_table': 'dbms_comments',
            },
        ),
    ]
