# Generated by Django 2.1.3 on 2019-04-25 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20190424_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorities',
            options={'ordering': ['name'], 'verbose_name_plural': '内部-权限'},
        ),
        migrations.AlterModelOptions(
            name='cartes',
            options={'ordering': ['ordery'], 'verbose_name_plural': '内部-菜单'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['name'], 'verbose_name_plural': '内部-岗位'},
        ),
        migrations.AddField(
            model_name='agrees',
            name='agree_sign',
            field=models.TextField(blank=True, null=True, verbose_name='签批单'),
        ),
        migrations.AddField(
            model_name='agrees',
            name='agree_view',
            field=models.TextField(blank=True, null=True, verbose_name='合同预览'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='warrant',
            field=models.ForeignKey(limit_choices_to={'warrant_typ': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='housebag_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='resultstate',
            name='result_typ',
            field=models.IntegerField(choices=[(11, '股东会决议'), (21, '董事会决议'), (31, '声明书'), (41, '单身声明')], verbose_name='决议类型'),
        ),
        migrations.AlterField(
            model_name='shareholders',
            name='shareholder_name',
            field=models.CharField(max_length=32, verbose_name='股东名称'),
        ),
    ]
