# Generated by Django 2.1.3 on 2019-01-04 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20190104_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='provide_repay_sum',
            field=models.FloatField(default=0, verbose_name='_还款金额'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provide_notify', to='A_dbms.Notify', verbose_name='_放款通知'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='providor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
    ]
