# Generated by Django 2.1 on 2020-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20200421_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='book',
            field=models.TextField(blank=True, null=True, verbose_name='专员台账'),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.TextField(blank=True, null=True, verbose_name='专员台账'),
        ),
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '已代偿'), (3, '诉前'), (11, '一审'), (21, '上诉及再审'), (31, '案外之诉'), (41, '执行'), (51, '终本'), (91, '结案')], default=1, verbose_name='追偿状态'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (5, '住宅、住宅地下室'), (11, '商业'), (12, '商业服务'), (13, '商业用房'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (47, '营业房'), (48, '研发中心'), (49, '研发楼'), (50, '研发车间'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (55, '倒班房及食堂'), (56, '农贸市场'), (57, '生产车间用房'), (58, '生产'), (59, '住宅、车库、住宅配套用房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (64, '机动车库'), (65, '机动车停车库'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (74, '连廊'), (75, '自行车库'), (76, '生产用房'), (77, '库房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (5, '住宅、住宅地下室'), (11, '商业'), (12, '商业服务'), (13, '商业用房'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (47, '营业房'), (48, '研发中心'), (49, '研发楼'), (50, '研发车间'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (55, '倒班房及食堂'), (56, '农贸市场'), (57, '生产车间用房'), (58, '生产'), (59, '住宅、车库、住宅配套用房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (64, '机动车库'), (65, '机动车停车库'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (74, '连廊'), (75, '自行车库'), (76, '生产用房'), (77, '库房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='letterguarantee',
            name='letter_typ',
            field=models.IntegerField(choices=[(1, '履约保函'), (11, '投标保函'), (21, '预付款保函'), (31, '质量与维修保函')], verbose_name='保函类型'),
        ),
        migrations.AlterField(
            model_name='resultstate',
            name='result_typ',
            field=models.IntegerField(choices=[(11, '股东会决议'), (13, '合伙人会议决议'), (15, '举办者会议决议'), (21, '董事会决议'), (23, '管委会决议'), (31, '财产声明书'), (41, '个人婚姻状况及财产申明'), (51, '承诺函'), (52, '承租人承诺书'), (99, '其他协议')], verbose_name='决议类型'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='credit_model',
            field=models.IntegerField(choices=[(1, '流动资金贷款'), (2, '银行承兑汇票敞口'), (3, '保函'), (4, '综合授信额度（含流贷、银承、保函）'), (31, '委托贷款'), (41, '按揭贷款')], default=1, verbose_name='授信类型'),
        ),
    ]
