# Generated by Django 2.1.3 on 2019-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20190212_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_blance',
            field=models.FloatField(default=0, verbose_name='_余额'),
        ),
        migrations.AddField(
            model_name='articles',
            name='article_balance',
            field=models.FloatField(default=0, verbose_name='_余额'),
        ),
        migrations.AddField(
            model_name='notify',
            name='notify_balance',
            field=models.FloatField(default=0, verbose_name='_余额'),
        ),
        migrations.AddField(
            model_name='provides',
            name='provide_balance',
            field=models.FloatField(default=0, verbose_name='_余额'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.CharField(choices=[('①', '①'), ('②', '②'), ('③', '③'), ('④', '④'), ('⑤', '⑤'), ('⑥', '⑥'), ('⑦', '⑦')], max_length=6, verbose_name='反担保种类数'),
        ),
    ]
