# Generated by Django 2.1.3 on 2019-01-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20190109_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperators',
            options={'verbose_name_plural': '外部-合作机构'},
        ),
    ]
