# Generated by Django 2.1.3 on 2019-02-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0016_auto_20190224_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dun',
            name='recovered_amount',
        ),
        migrations.AddField(
            model_name='dun',
            name='dun_charge_sun',
            field=models.FloatField(default=0, verbose_name='_追偿费用'),
        ),
        migrations.AddField(
            model_name='dun',
            name='dun_retrieve_sun',
            field=models.FloatField(default=0, verbose_name='_回收金额'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiry_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealup_seal', to='A_dbms.Seal', verbose_name='财产线索'),
        ),
    ]
