# Generated by Django 2.1 on 2020-07-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0017_auto_20200727_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customes',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
    ]
