# Generated by Django 2.1.7 on 2019-09-23 02:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0017_auto_20190905_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_typ',
            field=models.IntegerField(choices=[(1, '担保'), (5, '小贷'), (11, '租赁'), (21, '保险')], default=1, verbose_name='_项目状态'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='compere',
            field=models.ForeignKey(limit_choices_to={'employee_status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='compere_employee', to=settings.AUTH_USER_MODEL, verbose_name='主持人'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='review_model',
            field=models.IntegerField(choices=[(1, '内审'), (2, '外审'), (5, '签批'), (21, '小贷-评审'), (25, '小贷-签批')], verbose_name='评审类型'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='cooperator_type',
            field=models.IntegerField(choices=[(1, '金融机构'), (11, '律师事务所'), (21, '评估事务所'), (91, '其他机构')], default=1, verbose_name='机构类型'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (47, '营业房'), (48, '研发中心'), (49, '研发楼'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (64, '机动车库'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (74, '连廊'), (75, '自行车库'), (76, '生产用房'), (77, '库房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (47, '营业房'), (48, '研发中心'), (49, '研发楼'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (64, '机动车库'), (71, '仓储'), (72, '仓储用房及配送用房'), (73, '物流配送中心用房'), (74, '连廊'), (75, '自行车库'), (76, '生产用房'), (77, '库房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 9, 23), verbose_name='补调日期'),
        ),
    ]
