# Generated by Django 2.1.3 on 2019-02-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0017_compensatories_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customesp',
            name='spouses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_dbms.Customes', verbose_name='配偶'),
        ),
        migrations.AlterField(
            model_name='compensatories',
            name='dun_state',
            field=models.IntegerField(choices=[(1, '已代偿'), (3, '诉前'), (11, '已起诉'), (21, '已判决'), (31, '已和解'), (41, '执行中'), (91, '结案')], default=1, verbose_name='追偿状态'),
        ),
    ]
