# Generated by Django 2.1.3 on 2019-02-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0017_auto_20190213_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='notify_balance',
        ),
    ]
