# Generated by Django 2.1.3 on 2018-11-26 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0017_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='expert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='comment_expert', to='A_dbms.Experts', verbose_name='评委'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comments',
            name='num',
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('summary', 'expert')},
        ),
        migrations.RemoveField(
            model_name='singlequota',
            name='num',
        ),
        migrations.AlterUniqueTogether(
            name='singlequota',
            unique_together={('summary', 'credit_model')},
        ),
    ]
