# Generated by Django 2.1.3 on 2019-04-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0017_auto_20190425_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='counter_view',
            field=models.TextField(blank=True, null=True, verbose_name='合同预览'),
        ),
    ]
