# Generated by Django 2.1.3 on 2019-01-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0018_auto_20190109_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='agreeesextend',
            name='agree',
            field=models.OneToOneField(limit_choices_to={'counter_only': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='extend_agree', to='A_dbms.Agrees', verbose_name='委托合同'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='custom',
            field=models.ForeignKey(limit_choices_to={'agree_state': 11}, on_delete=django.db.models.deletion.PROTECT, related_name='article_custom', to='A_dbms.Customes', verbose_name='客户'),
        ),
    ]
