# Generated by Django 2.1.3 on 2019-02-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0018_auto_20190228_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customesp',
            name='spouses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouses_custom', to='A_dbms.Customes', verbose_name='配偶'),
        ),
    ]
