# Generated by Django 2.1.3 on 2019-04-25 07:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0018_counters_counter_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trustee_name', models.CharField(max_length=32, verbose_name='股东名称')),
                ('trusteeor_date', models.DateField(default=datetime.date.today, verbose_name='创建时间')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustee_custom_c', to='A_dbms.CustomesC', verbose_name='企业客户')),
                ('trusteeor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trusteeor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '客户-董事信息',
                'db_table': 'dbms_trustee',
            },
        ),
        migrations.AlterUniqueTogether(
            name='trustee',
            unique_together={('custom', 'trustee_name')},
        ),
    ]
