# Generated by Django 2.1.3 on 2019-02-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0018_remove_notify_notify_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agrees',
            name='agree_blance',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='article_balance',
        ),
        migrations.RemoveField(
            model_name='provides',
            name='provide_balance',
        ),
    ]
