# Generated by Django 2.1.3 on 2018-11-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0018_auto_20181126_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlequota',
            name='amount',
            field=models.FloatField(default=0, verbose_name='放款金额'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_type',
            field=models.IntegerField(choices=[(1, '同意'), (2, '复议'), (3, '不同意')], default=1, verbose_name='评委意见'),
        ),
    ]
