# Generated by Django 2.1.3 on 2019-02-28 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0019_auto_20190228_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customesp',
            name='spouse',
        ),
        migrations.AlterField(
            model_name='customesp',
            name='spouses',
            field=models.OneToOneField(blank=True, limit_choices_to={'genre': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spouses_custom', to='A_dbms.Customes', verbose_name='配偶'),
        ),
    ]
