# Generated by Django 2.1.3 on 2018-11-27 01:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0019_auto_20181126_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='收费金额')),
                ('charge_date', models.DateField(default=datetime.date.today, verbose_name='收费日期')),
                ('balance', models.FloatField(verbose_name='应收余额')),
            ],
            options={
                'db_table': 'dbms_charges',
                'verbose_name_plural': '放款-收费',
            },
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_balance',
            field=models.FloatField(default=0, verbose_name='_放款金额（元）'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='amount',
            field=models.FloatField(default=0, verbose_name='_放款金额（元）'),
        ),
        migrations.AddField(
            model_name='charges',
            name='agree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_agree', to='A_dbms.Agrees', verbose_name='委托保证合同'),
        ),
    ]
