# Generated by Django 2.1.3 on 2019-01-10 07:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0019_auto_20190109_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_repayment_sum',
            field=models.FloatField(default=0, verbose_name='_还款金额'),
        ),
        migrations.AddField(
            model_name='repayments',
            name='repaymentdate',
            field=models.DateField(default=datetime.date.today, verbose_name='_创建日期'),
        ),
        migrations.AlterField(
            model_name='repayments',
            name='provide',
            field=models.ForeignKey(limit_choices_to={'provide_status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='repayment_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
    ]
