# Generated by Django 2.1.3 on 2019-04-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0019_auto_20190425_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customesc',
            name='decisionor',
            field=models.IntegerField(choices=[(11, '股东会'), (21, '董事会')], default=11, verbose_name='决策机构'),
        ),
    ]
