# Generated by Django 2.1.3 on 2019-02-15 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0019_auto_20190213_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='lending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agree_lending', to='A_dbms.LendingOrder', verbose_name='放款纪要'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee_job', to='A_dbms.Jobs'),
        ),
        migrations.AlterField(
            model_name='lendingorder',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lending_summary', to='A_dbms.Articles', verbose_name='项目纪要'),
        ),
    ]
