# Generated by Django 2.1.3 on 2019-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0020_auto_20190228_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (61, '车库'), (71, '仓储'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
    ]
