# Generated by Django 2.1.3 on 2019-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0020_auto_20190110_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provides',
            old_name='provide_repay_sum',
            new_name='provide_repayment_sum',
        ),
        migrations.AddField(
            model_name='agrees',
            name='agree_repayment_sum',
            field=models.FloatField(default=0, verbose_name='_还款金额'),
        ),
        migrations.AddField(
            model_name='lendingorder',
            name='lending_repayment_sum',
            field=models.FloatField(default=0, verbose_name='_还款金额'),
        ),
        migrations.AddField(
            model_name='notify',
            name='notify_repayment_sum',
            field=models.FloatField(default=0, verbose_name='_还款金额'),
        ),
    ]
