# Generated by Django 2.1.3 on 2018-11-27 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0020_auto_20181127_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='charge',
            field=models.FloatField(default=0, verbose_name='应收保费（元）'),
        ),
        migrations.AlterField(
            model_name='charges',
            name='agree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_agree', to='A_dbms.Agrees', verbose_name='委托合同'),
        ),
    ]
