# Generated by Django 2.1.3 on 2019-04-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0020_customesc_decisionor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustee',
            name='trustee_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='董事姓名'),
        ),
    ]
