# Generated by Django 2.1.3 on 2019-02-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0020_auto_20190215_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='job',
            field=models.ManyToManyField(blank=True, null=True, to='A_dbms.Jobs'),
        ),
    ]
