# Generated by Django 2.1.3 on 2019-02-16 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0021_auto_20190215_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('url_name', models.CharField(max_length=128, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': '内部-权限',
                'db_table': 'dbms_authorities',
            },
        ),
        migrations.CreateModel(
            name='Cartes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('url_name', models.CharField(max_length=128, verbose_name='URL')),
                ('ordery', models.IntegerField(verbose_name='优先级')),
            ],
            options={
                'verbose_name_plural': '内部-菜单',
                'db_table': 'dbms_cartes',
            },
        ),
        migrations.AlterField(
            model_name='jobs',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='A_dbms.Menus', verbose_name='菜单'),
        ),
        migrations.AlterUniqueTogether(
            name='cartes',
            unique_together={('name', 'url_name')},
        ),
        migrations.AddField(
            model_name='authorities',
            name='carte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_carte', to='A_dbms.Cartes', verbose_name='菜单'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='authority',
            field=models.ManyToManyField(blank=True, null=True, to='A_dbms.Authorities', verbose_name='权限'),
        ),
        migrations.AlterUniqueTogether(
            name='authorities',
            unique_together={('name', 'url_name')},
        ),
    ]
