# Generated by Django 2.1.3 on 2019-03-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0021_auto_20190228_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chattel',
            options={'verbose_name_plural': '权证-其他'},
        ),
        migrations.RemoveField(
            model_name='cartes',
            name='parrent',
        ),
        migrations.AddField(
            model_name='cartes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carte_parent', to='A_dbms.Cartes', verbose_name='母菜单'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='chattel_typ',
            field=models.IntegerField(choices=[(1, '存货'), (11, '设备'), (21, '合格证'), (31, '专利'), (41, '商标'), (71, '账户'), (99, '其他')], default=1, verbose_name='动产种类'),
        ),
        migrations.AlterField(
            model_name='compensatories',
            name='dun_state',
            field=models.IntegerField(choices=[(1, '已代偿'), (3, '诉前'), (11, '一审'), (21, '上诉及再审'), (31, '案外之诉'), (41, '执行'), (91, '结案')], default=1, verbose_name='追偿状态'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(error_messages={'unique': 'E-mail已经存在！'}, max_length=150, unique=True, verbose_name='电子邮箱'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='share',
            field=models.FloatField(verbose_name='数量（万）'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='auction_state',
            field=models.IntegerField(choices=[(1, '正常'), (2, '查封'), (3, '评估'), (5, '挂网'), (11, '成交'), (21, '流拍'), (31, '回转'), (99, '注销')], default=1, verbose_name='_拍卖状态'),
        ),
    ]
