# Generated by Django 2.1.3 on 2019-04-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0021_auto_20190425_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='counter_state',
            field=models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '作废')], default=21, verbose_name='签订状态'),
        ),
    ]
