# Generated by Django 2.1.3 on 2018-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0021_auto_20181127_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisals',
            name='article',
            field=models.ManyToManyField(related_name='appraisal_article', to='A_dbms.Articles', verbose_name='参评项目'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='expert',
            field=models.ManyToManyField(related_name='article_expert', to='A_dbms.Experts', verbose_name='评审委员'),
        ),
        migrations.AlterField(
            model_name='summaries',
            name='expert',
            field=models.ManyToManyField(related_name='summary_expert', to='A_dbms.Experts', verbose_name='评审委员'),
        ),
    ]
