# Generated by Django 2.1.3 on 2019-04-28 06:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0022_auto_20190426_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(verbose_name='计划日期')),
                ('proceed', models.CharField(max_length=128, verbose_name='跟踪内容')),
                ('track_date', models.DateField(blank=True, null=True, verbose_name='跟踪日期')),
                ('condition', models.TextField(blank=True, null=True, verbose_name='跟踪情况')),
                ('track_state', models.IntegerField(choices=[(11, '待跟踪'), (21, '已跟踪')], default=11, verbose_name='跟踪状态')),
                ('trackordate', models.DateField(default=datetime.date.today, verbose_name='_创建日期')),
                ('provide', models.ForeignKey(limit_choices_to={'provide_status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='track_provide', to='A_dbms.Provides', verbose_name='放款')),
                ('trackor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者')),
            ],
            options={
                'verbose_name_plural': '项目-跟踪',
                'db_table': 'dbms_track',
            },
        ),
        migrations.AlterField(
            model_name='repayments',
            name='repaymentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repaymentor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
    ]
