# Generated by Django 2.1.3 on 2019-03-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0022_auto_20190302_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartes',
            old_name='name',
            new_name='caption',
        ),
    ]
