# Generated by Django 2.1.3 on 2019-02-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0022_auto_20190216_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartes',
            name='parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carte_parrent', to='A_dbms.Cartes', verbose_name='母菜单'),
        ),
    ]
