# Generated by Django 2.1.3 on 2019-01-11 01:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0022_auto_20190111_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='providordate',
            field=models.DateField(default=datetime.date.today, verbose_name='_创建日期'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='due_date',
            field=models.DateField(verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_date',
            field=models.DateField(verbose_name='放款日期'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_repayment_sum',
            field=models.FloatField(default=0, verbose_name='_还款总额'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_typ',
            field=models.IntegerField(choices=[(1, '流贷'), (11, '承兑'), (12, '保函')], verbose_name='放款种类'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='providor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
    ]
