# Generated by Django 2.1.3 on 2019-02-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0023_cartes_parrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartes',
            name='url_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
