# Generated by Django 2.1.3 on 2018-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0023_auto_20181128_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisals',
            name='review_year',
            field=models.IntegerField(default=2018, verbose_name='评审年份'),
        ),
    ]
