# Generated by Django 2.1.3 on 2019-03-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0023_auto_20190302_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorities',
            name='url',
            field=models.CharField(default=1, max_length=128, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
