# Generated by Django 2.1.3 on 2019-01-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0023_auto_20190111_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provides',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (11, '暂存风控'), (21, '已归档')], default=1, verbose_name='_归档状态'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_status',
            field=models.IntegerField(choices=[(1, '在保'), (11, '解保'), (21, '代偿')], default=1, verbose_name='_放款状态'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_typ',
            field=models.IntegerField(choices=[(1, '流贷'), (11, '承兑'), (21, '保函')], verbose_name='放款种类'),
        ),
    ]
