# Generated by Django 2.1.3 on 2019-03-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0024_authorities_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorities',
            name='url_name',
            field=models.CharField(max_length=128, unique=True, verbose_name='URL_NAME'),
        ),
    ]
