# Generated by Django 2.1.3 on 2019-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0024_auto_20190111_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customes',
            old_name='accept_loan',
            new_name='custom_accept',
        ),
        migrations.RenameField(
            model_name='customes',
            old_name='back_loan',
            new_name='custom_back',
        ),
        migrations.RenameField(
            model_name='customes',
            old_name='flow_loan',
            new_name='custom_flow',
        ),
        migrations.RemoveField(
            model_name='cooperators',
            name='back_loan',
        ),
        migrations.RemoveField(
            model_name='cooperators',
            name='back_used',
        ),
        migrations.RemoveField(
            model_name='cooperators',
            name='flow_loan',
        ),
        migrations.RemoveField(
            model_name='cooperators',
            name='flow_used',
        ),
        migrations.AddField(
            model_name='branches',
            name='branch_accept',
            field=models.FloatField(default=0, verbose_name='_承兑余额'),
        ),
        migrations.AddField(
            model_name='branches',
            name='branch_back',
            field=models.FloatField(default=0, verbose_name='_保函余额'),
        ),
        migrations.AddField(
            model_name='branches',
            name='branch_flow',
            field=models.FloatField(default=0, verbose_name='_流贷余额'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='cooperator_state',
            field=models.IntegerField(choices=[(1, '金融机构'), (11, '律师事务所'), (21, '评估事务所')], default=1, verbose_name='机构类型'),
        ),
    ]
