# Generated by Django 2.1.3 on 2018-11-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0024_appraisals_review_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisals',
            name='expert',
        ),
    ]
