# Generated by Django 2.1.3 on 2019-04-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0024_auto_20190428_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['plan_date'], 'verbose_name_plural': '放款-跟踪'},
        ),
        migrations.AddField(
            model_name='track',
            name='track_typ',
            field=models.IntegerField(choices=[(11, '日常跟踪'), (21, '分期还款'), (25, '分期付息'), (31, '提前还款')], default=11, verbose_name='跟踪类型'),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_state',
            field=models.IntegerField(choices=[(11, '待跟踪'), (21, '已跟踪')], default=11, verbose_name='_跟踪状态'),
        ),
    ]
