# Generated by Django 2.1.3 on 2019-02-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0024_auto_20190216_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartes',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='菜单名称'),
        ),
        migrations.AlterUniqueTogether(
            name='cartes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartes',
            name='url_name',
        ),
    ]
