# Generated by Django 2.1.3 on 2019-01-14 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0025_auto_20190113_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='custom',
            field=models.ForeignKey(limit_choices_to={'counter_only': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='article_custom', to='A_dbms.Customes', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='email',
            field=models.CharField(max_length=32, verbose_name='邮箱'),
        ),
    ]
