# Generated by Django 2.1.3 on 2019-02-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0025_auto_20190217_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftextend',
            name='draft_state',
            field=models.IntegerField(choices=[(1, '未入库'), (2, '已入库'), (21, '置换出库'), (31, '解保出库'), (41, '托收出库'), (99, '已注销')], default=1, verbose_name='_票据状态'),
        ),
    ]
