# Generated by Django 2.1.3 on 2018-11-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0025_remove_appraisals_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaries',
            name='appraisal',
        ),
        migrations.RemoveField(
            model_name='summaries',
            name='article',
        ),
        migrations.RemoveField(
            model_name='summaries',
            name='expert',
        ),
        migrations.DeleteModel(
            name='Summaries',
        ),
    ]
