# Generated by Django 2.1.3 on 2019-03-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0025_auto_20190303_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorities',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='URL'),
        ),
    ]
