# Generated by Django 2.1.3 on 2019-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0025_auto_20190429_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='_纪要'),
        ),
    ]
