# Generated by Django 2.1.3 on 2019-05-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0026_articles_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlequota',
            name='rate',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='收费标准'),
        ),
    ]
