# Generated by Django 2.1.3 on 2018-11-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0026_auto_20181130_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisals',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, related_name='appraisal_article', to='A_dbms.Articles', verbose_name='参评项目'),
        ),
    ]
