# Generated by Django 2.1.3 on 2019-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0026_auto_20190114_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrants',
            name='warrant_detail',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (5, '土地'), (11, '应收'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '动产'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
    ]
