# Generated by Django 2.1.3 on 2019-03-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0026_auto_20190303_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorities',
            name='ordery',
            field=models.IntegerField(blank=True, null=True, verbose_name='优先级'),
        ),
    ]
