# Generated by Django 2.1.3 on 2019-01-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0027_auto_20190115_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrants',
            name='warrant_num',
            field=models.CharField(max_length=64, unique=True, verbose_name='权证编码'),
        ),
    ]
