# Generated by Django 2.1.3 on 2019-03-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0027_authorities_ordery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='menu',
        ),
    ]
