# Generated by Django 2.1.3 on 2019-02-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0027_auto_20190221_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='dun',
            name='dun_amount',
            field=models.FloatField(default=0, verbose_name='追偿金额'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='guarantee_typ',
            field=models.CharField(choices=[('①', '①'), ('②', '②'), ('③', '③'), ('④', '④'), ('⑤', '⑤'), ('⑥', '⑥'), ('⑦', '⑦'), ('⑧', '⑧')], max_length=6, verbose_name='反担保种类数'),
        ),
    ]
