# Generated by Django 2.1.3 on 2019-05-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0027_singlequota_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequota',
            name='flow_rate',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='费率'),
        ),
    ]
