# Generated by Django 2.1.3 on 2018-12-02 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0027_auto_20181130_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='level',
            field=models.IntegerField(choices=[(0, '内部'), (1, '一级'), (2, '二级')], default=1, verbose_name='级别'),
        ),
    ]
