# Generated by Django 2.1.3 on 2019-02-21 06:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0028_auto_20190221_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='dun',
            name='dun_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='dun',
            name='dunor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dunor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dun',
            name='recovered_amount',
            field=models.FloatField(default=0, verbose_name='回收金额'),
        ),
    ]
