# Generated by Django 2.1.3 on 2018-12-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0028_auto_20181202_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_order',
            field=models.IntegerField(default=1, verbose_name='合同序号'),
            preserve_default=False,
        ),
    ]
