# Generated by Django 2.1.3 on 2019-03-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0028_remove_jobs_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menus',
        ),
    ]
