# Generated by Django 2.1.3 on 2019-05-05 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0028_auto_20190505_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlequota',
            name='rate',
        ),
    ]
