# Generated by Django 2.1.3 on 2019-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0029_auto_20190221_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '起诉'), (11, '判决'), (21, '执行'), (31, '和解结案'), (41, '终止执行')], default=1, verbose_name='追偿状态'),
        ),
    ]
