# Generated by Django 2.1.3 on 2019-05-05 07:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0029_remove_singlequota_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='补调问题')),
                ('supply_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_summary', to='A_dbms.Articles', verbose_name='纪要')),
                ('supplyor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplyor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'dbms_supply',
                'verbose_name_plural': '评审-额度',
            },
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='single_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='single_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
