# Generated by Django 2.1.3 on 2019-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0029_delete_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreeesextend',
            name='agree',
        ),
        migrations.AlterField(
            model_name='dun',
            name='dun_stage',
            field=models.IntegerField(choices=[(1, '已代偿'), (3, '诉前'), (11, '一审'), (21, '上诉及再审'), (31, '案外之诉'), (41, '执行'), (91, '结案')], default=1, verbose_name='追偿状态'),
        ),
        migrations.DeleteModel(
            name='AgreeesExtend',
        ),
    ]
