# Generated by Django 2.1.3 on 2019-01-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0029_auto_20190115_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='concrete',
            field=models.TextField(default='-', verbose_name='意见详情'),
            preserve_default=False,
        ),
    ]
