# Generated by Django 2.1.3 on 2019-05-05 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0030_auto_20190505_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name_plural': '评审-补调问题'},
        ),
        migrations.AlterField(
            model_name='others',
            name='other_typ',
            field=models.IntegerField(choices=[(11, '购房合同'), (21, '合格证'), (31, '专利'), (41, '商标'), (71, '账户'), (99, '其他')], default=99, verbose_name='资产种类'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_summary', to='A_dbms.Articles', verbose_name='项目'),
        ),
    ]
