# Generated by Django 2.1.3 on 2019-01-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0030_auto_20190115_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='classification',
            field=models.FloatField(default=1, verbose_name='_风险分类'),
        ),
    ]
