# Generated by Django 2.1.3 on 2019-02-21 07:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0030_auto_20190221_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_agree', models.CharField(max_length=128, unique=True, verbose_name='代理合同')),
                ('agent_item', models.TextField(verbose_name='代理事项')),
                ('fee_scale', models.TextField(verbose_name='收费标准')),
                ('agent_term', models.IntegerField(verbose_name='代理期限(年)')),
                ('agent_date', models.DateField(verbose_name='代理日期')),
                ('agent_state', models.IntegerField(choices=[(1, '生效'), (11, '失效'), (99, '注销')], default=1, verbose_name='合同状态')),
                ('agent_remark', models.TextField(verbose_name='备注')),
                ('agentor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('agentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agentor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('dun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_dun', to='A_dbms.Dun', verbose_name='追偿项目')),
            ],
            options={
                'db_table': 'dbms_agent',
                'verbose_name_plural': '追偿-代理合同',
            },
        ),
    ]
