# Generated by Django 2.1.3 on 2019-03-07 11:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0030_auto_20190306_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_credit', models.FloatField(default=100000000, verbose_name='综合额度')),
                ('flow_limit', models.FloatField(default=10000000, verbose_name='单笔限额（综合）')),
                ('back_credit', models.FloatField(default=0, verbose_name='保函额度')),
                ('back_limit', models.FloatField(default=0, verbose_name='单笔限额（保函）')),
                ('credit_date', models.DateField(default=datetime.date.today, verbose_name='合作日期')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='到期日')),
                ('agreementor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
            ],
            options={
                'verbose_name_plural': '外部-合作协议',
                'db_table': 'dbms_agreements',
            },
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_status',
            field=models.IntegerField(choices=[(1, '在职'), (11, '离职')], default=1, verbose_name='_员工状态'),
        ),
        migrations.AlterField(
            model_name='pigeonholes',
            name='pigeonhole_transfer',
            field=models.ForeignKey(limit_choices_to={'employee_status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='pigeonhole_transfer_employee', to=settings.AUTH_USER_MODEL, verbose_name='移交人'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='transfer',
            field=models.ForeignKey(limit_choices_to={'employee_status': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_employee', to=settings.AUTH_USER_MODEL, verbose_name='移交/接收者'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='agreementor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreementor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='agreements',
            name='cooperator',
            field=models.ForeignKey(limit_choices_to={'agreement_state': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_cooperator', to='A_dbms.Cooperators', verbose_name='合作机构'),
        ),
    ]
