# Generated by Django 2.1.3 on 2018-12-04 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0030_auto_20181204_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='build_date',
        ),
    ]
