# Generated by Django 2.1.3 on 2019-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0031_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_item',
            field=models.TextField(blank=True, null=True, verbose_name='代理事项'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_term',
            field=models.IntegerField(blank=True, null=True, verbose_name='代理期限(年)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='fee_scale',
            field=models.TextField(blank=True, null=True, verbose_name='收费标准'),
        ),
    ]
