# Generated by Django 2.1.3 on 2018-12-04 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0031_remove_articles_build_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agree_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
