# Generated by Django 2.1.3 on 2019-05-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0031_auto_20190505_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_rate',
            field=models.CharField(default='', max_length=128, verbose_name='收费'),
            preserve_default=False,
        ),
    ]
