# Generated by Django 2.1.3 on 2019-03-07 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0031_auto_20190307_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperators',
            name='cooperat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cooperat_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='cooperators',
            name='cooperat_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='cooperator',
            field=models.ForeignKey(limit_choices_to={'cooperator_state': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='agreement_cooperator', to='A_dbms.Cooperators', verbose_name='合作机构'),
        ),
    ]
