# Generated by Django 2.1.3 on 2018-12-04 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0032_agrees_agree_buildor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisals',
            name='meeting_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='meeting_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
