# Generated by Django 2.1.3 on 2019-02-21 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0032_auto_20190221_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=128, unique=True, verbose_name='代理合同')),
                ('staff_type', models.IntegerField(choices=[(1, '代理律师'), (11, '审判法官'), (21, '执行法官'), (31, '评估人员'), (41, '代理员工'), (99, '其他人员')], verbose_name='人员类型')),
                ('contact_number', models.CharField(max_length=32, verbose_name='联系电话')),
                ('agent_item', models.TextField(blank=True, null=True, verbose_name='代理事项')),
                ('staff_remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('staffor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('dun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_dun', to='A_dbms.Dun', verbose_name='追偿项目')),
                ('staffor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'db_table': 'dbms_staff',
                'verbose_name_plural': '追偿-人员',
            },
        ),
    ]
