# Generated by Django 2.1.3 on 2019-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0032_agrees_agree_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='denomination',
            field=models.FloatField(default=0, verbose_name='票面金额'),
            preserve_default=False,
        ),
    ]
