# Generated by Django 2.1.3 on 2019-03-07 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0032_auto_20190307_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperators',
            name='cooperat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cooperat_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
