# Generated by Django 2.1.3 on 2019-01-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0033_auto_20190117_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='convenor_opinion',
            field=models.TextField(blank=True, null=True, verbose_name='招集人意见'),
        ),
        migrations.AddField(
            model_name='articles',
            name='rcd_opinion',
            field=models.TextField(blank=True, null=True, verbose_name='风控部意见'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '已反馈'), (3, '待上会'), (4, '已上会'), (5, '已签批'), (6, '已注销'), (7, '已放完')], default=1, verbose_name='_项目状态'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='ground_app',
            field=models.IntegerField(choices=[(1, '住宅'), (5, '城镇混合住宅用地'), (11, '商住'), (21, '商服'), (31, '工业')], default=1, verbose_name='土地用途'),
        ),
    ]
