# Generated by Django 2.1.3 on 2019-02-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0033_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.IntegerField(choices=[(1, '代理律师'), (11, '审判法官'), (21, '执行法官'), (31, '评估人员'), (41, '代理员工'), (51, '助拍人员'), (99, '其他人员')], verbose_name='人员类型'),
        ),
    ]
