# Generated by Django 2.1.3 on 2019-03-07 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0033_auto_20190307_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='branchor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='branchor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='branchor_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='experts',
            name='expertor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expertor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experts',
            name='expertor_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='back_credit',
            field=models.FloatField(blank=True, null=True, verbose_name='保函额度'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='back_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='单笔限额（保函）'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='credit_date',
            field=models.DateField(blank=True, null=True, verbose_name='合作日期'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='flow_credit',
            field=models.FloatField(blank=True, null=True, verbose_name='综合额度'),
        ),
        migrations.AlterField(
            model_name='cooperators',
            name='flow_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='单笔限额（综合）'),
        ),
    ]
