# Generated by Django 2.1.3 on 2019-05-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0033_draft_denomination'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='draft_typ',
            field=models.IntegerField(choices=[(11, '商业承兑汇票'), (21, '银行承兑汇票'), (31, '支票')], default=1, verbose_name='票据种类'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='denomination',
            field=models.FloatField(verbose_name='票面总额'),
        ),
    ]
