# Generated by Django 2.1.3 on 2019-02-21 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0034_auto_20190221_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=128, unique=True, verbose_name='代理合同')),
                ('charge_type', models.IntegerField(choices=[(1, '律师代理费'), (11, '案件受理费'), (21, '财产保全费'), (31, '执行费'), (41, '公告费'), (99, '其他费用')], verbose_name='人员类型')),
                ('charge_amount', models.FloatField(verbose_name='金额')),
                ('charge_remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('chargor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_dun', to='A_dbms.Dun', verbose_name='追偿项目')),
                ('chargor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': '追偿-追偿费用',
                'db_table': 'dbms_charge',
            },
        ),
    ]
