# Generated by Django 2.1.3 on 2019-01-17 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0034_auto_20190117_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='ascertain_date',
            field=models.DateField(default=datetime.date.today, verbose_name='落实日期'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='sign_detail',
            field=models.TextField(blank=True, null=True, verbose_name='签批人意见'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='ground_app',
            field=models.IntegerField(choices=[(1, '住宅'), (5, '城镇混合住宅'), (11, '商住'), (21, '商服'), (31, '工业')], default=1, verbose_name='土地用途'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='ground_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
