# Generated by Django 2.1.3 on 2019-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0034_auto_20190307_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='back_limit',
            field=models.FloatField(default=0, verbose_name='单笔（保函）'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='flow_limit',
            field=models.FloatField(default=10000000, verbose_name='单笔（综合）'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_locate',
            field=models.CharField(max_length=128, unique=True, verbose_name='房产坐落'),
        ),
    ]
