# Generated by Django 2.1.3 on 2019-05-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0034_auto_20190508_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='draft_typ',
        ),
        migrations.AddField(
            model_name='draft',
            name='typ',
            field=models.IntegerField(choices=[(11, '商业承兑汇票'), (21, '银行承兑汇票'), (31, '支票')], default=11, verbose_name='票据种类'),
        ),
    ]
