# Generated by Django 2.1.3 on 2019-01-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0035_auto_20190117_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '未落实'), (41, '部分落实'), (51, '已落实'), (51, '待变更'), (61, '已解保'), (99, '已作废')], default=11, verbose_name='_合同状态'),
        ),
    ]
