# Generated by Django 2.1.3 on 2019-05-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0035_auto_20190508_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='cost',
            field=models.FloatField(default=0, verbose_name='价值'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='others',
            name='other_typ',
            field=models.IntegerField(choices=[(11, '购房合同'), (21, '车辆合格证'), (31, '专利'), (41, '商标'), (71, '账户'), (99, '其他')], default=99, verbose_name='资产种类'),
        ),
    ]
