# Generated by Django 2.1.3 on 2019-02-21 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0035_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_date',
            field=models.DateField(default=datetime.date.today, verbose_name='支付日期'),
        ),
    ]
