# Generated by Django 2.1.3 on 2018-12-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0035_singlequota_single_buildor'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='ordery',
            field=models.IntegerField(default=1, verbose_name='优先级'),
            preserve_default=False,
        ),
    ]
