# Generated by Django 2.1.3 on 2019-03-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0036_auto_20190308_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='balance',
            field=models.FloatField(default=0, verbose_name='_在保余额'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='ground_app',
            field=models.IntegerField(choices=[(1, '住宅'), (5, '城镇混合住宅'), (11, '商住'), (21, '商服'), (31, '工业'), (91, '林权')], default=1, verbose_name='土地用途'),
        ),
    ]
