# Generated by Django 2.1.3 on 2018-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0036_experts_ordery'),
    ]

    operations = [
        migrations.AddField(
            model_name='experts',
            name='expert_state',
            field=models.IntegerField(choices=[(1, '正常'), (2, '注销')], default=1, verbose_name='评审状态'),
        ),
    ]
