# Generated by Django 2.1.3 on 2019-01-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0036_auto_20190117_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='counter_remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '未落实'), (41, '已落实'), (51, '待变更'), (61, '已解保'), (99, '已作废')], default=11, verbose_name='_合同状态'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_state',
            field=models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '已作废')], default=11, verbose_name='_签订情况'),
        ),
    ]
