# Generated by Django 2.1.3 on 2019-05-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0036_auto_20190509_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='review_amount',
            field=models.IntegerField(default=0, verbose_name='保后次数'),
        ),
        migrations.AlterField(
            model_name='others',
            name='cost',
            field=models.FloatField(verbose_name='价值（元）'),
        ),
    ]
