# Generated by Django 2.1.3 on 2019-01-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0037_auto_20190118_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='counters',
            name='counter_sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='签订日期'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_state',
            field=models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '已作废')], default=11, verbose_name='状态'),
        ),
    ]
