# Generated by Django 2.1.3 on 2018-12-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0037_experts_expert_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '待上会'), (3, '无补调'), (4, '无补调'), (5, '需补调'), (6, '已补调'), (7, '已签批')], default=1, verbose_name='项目状态'),
        ),
    ]
