# Generated by Django 2.1.3 on 2019-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0037_auto_20190311_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provides',
            name='balance',
            field=models.FloatField(verbose_name='_在保余额'),
        ),
    ]
