# Generated by Django 2.1.3 on 2019-02-21 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0037_auto_20190221_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=128, unique=True, verbose_name='代理合同')),
                ('retrieve_type', models.IntegerField(choices=[(1, '诉讼前清收'), (11, '履行判决'), (21, '强制执行'), (21, '执行资产抵债'), (99, '其他回收方式')], verbose_name='回收类型')),
                ('retrieve_amount', models.FloatField(verbose_name='金额')),
                ('retrieve_date', models.DateField(verbose_name='回收日期')),
                ('retrieve_remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('retrievor_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('dun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrieve_dun', to='A_dbms.Dun', verbose_name='追偿项目')),
                ('retrievor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retrievor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': '追偿-案款回收',
                'db_table': 'dbms_retrieve',
            },
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='charge',
            new_name='dun',
        ),
    ]
