# Generated by Django 2.1.3 on 2019-05-14 00:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0037_auto_20190514_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_typ', models.IntegerField(choices=[(11, '超时未投放补调'), (21, '分次发放补调'), (31, '变更补调')], verbose_name='_补调类型')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='风险分析')),
                ('suggestion', models.TextField(blank=True, null=True, verbose_name='风控建议')),
                ('classification', models.IntegerField(blank=True, choices=[(1, '正常'), (11, '关注'), (21, '次级'), (31, '可疑'), (41, '损失')], null=True, verbose_name='风险分类')),
                ('inv_date', models.DateField(default=datetime.date(2019, 5, 14), verbose_name='补调日期')),
            ],
            options={
                'db_table': 'dbms_investigate',
                'ordering': ['inv_date'],
                'verbose_name_plural': '项目-补调',
            },
        ),
        migrations.AlterField(
            model_name='customes',
            name='review_amount',
            field=models.IntegerField(default=0, verbose_name='年度调查'),
        ),
        migrations.AddField(
            model_name='investigate',
            name='custom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inv_custom', to='A_dbms.Customes', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='investigate',
            name='invor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invor_employee', to=settings.AUTH_USER_MODEL, verbose_name='补调人员'),
        ),
    ]
