# Generated by Django 2.1.3 on 2019-02-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0038_auto_20190221_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retrieve',
            name='staff_name',
        ),
    ]
