# Generated by Django 2.1.3 on 2019-05-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0038_auto_20190514_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigate',
            old_name='analysis',
            new_name='i_analysis',
        ),
        migrations.RenameField(
            model_name='investigate',
            old_name='classification',
            new_name='i_classification',
        ),
        migrations.RenameField(
            model_name='investigate',
            old_name='suggestion',
            new_name='i_suggestion',
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_typ',
            field=models.IntegerField(choices=[(11, '超时未投放补调'), (21, '分次发放补调'), (31, '变更补调')], verbose_name='补调类型'),
        ),
    ]
