# Generated by Django 2.1.3 on 2019-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0038_auto_20190118_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '未落实'), (41, '已落实'), (51, '待变更'), (61, '已解保'), (99, '已作废')], default=11, verbose_name='合同状态'),
        ),
    ]
