# Generated by Django 2.1.3 on 2019-01-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0039_auto_20190118_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='file_num',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='档案编号'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_remark',
            field=models.TextField(blank=True, null=True, verbose_name='落实情况'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '未落实'), (41, '已落实'), (51, '待变更'), (61, '已解保'), (99, '作废')], default=11, verbose_name='合同状态'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='ascertain_date',
            field=models.DateField(blank=True, null=True, verbose_name='落实日期'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '已反馈'), (3, '待上会'), (4, '已上会'), (5, '已签批'), (51, '已放完'), (99, '已注销')], default=1, verbose_name='_项目状态'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_remark',
            field=models.TextField(blank=True, null=True, verbose_name='签订备注'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_state',
            field=models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '作废')], default=11, verbose_name='签订状态'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='propose',
            field=models.IntegerField(choices=[(1, '符合上会条件'), (11, '暂不符合上会条件'), (21, '建议终止项目')], default=0, verbose_name='上会建议'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_sty',
            field=models.IntegerField(choices=[(1, '现场检查'), (11, '电话回访')], default=1, verbose_name='保后方式'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='storage_typ',
            field=models.IntegerField(choices=[(1, '入库'), (2, '续抵出库'), (11, '借出'), (12, '归还'), (31, '解保出库')], default=1, verbose_name='出入库'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_state',
            field=models.IntegerField(choices=[(1, '未入库'), (2, '已入库'), (6, '无需入库'), (11, '续抵出库'), (21, '已借出'), (31, '解保出库'), (99, '已注销')], default=1, verbose_name='_权证状态'),
        ),
    ]
