# Generated by Django 2.1.3 on 2019-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0039_auto_20190311_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='notify_balance',
            field=models.FloatField(default=0, verbose_name='_在保余额'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '已反馈'), (3, '待上会'), (4, '已上会'), (5, '已签批'), (51, '已放款'), (52, '已放完'), (55, '已解保'), (61, '待变更'), (99, '已注销')], default=1, verbose_name='_项目状态'),
        ),
    ]
