# Generated by Django 2.1.3 on 2019-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0039_auto_20190514_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingorder',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_typ',
            field=models.IntegerField(choices=[(11, '超时补调'), (21, '分次补调')], verbose_name='补调类型'),
        ),
    ]
