# Generated by Django 2.1.3 on 2019-02-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0039_remove_retrieve_staff_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dun',
            old_name='dun_date',
            new_name='dunor_date',
        ),
    ]
