# Generated by Django 2.1.3 on 2019-03-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0040_auto_20190311_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_balance',
            field=models.FloatField(default=0, verbose_name='_在保余额'),
        ),
    ]
