# Generated by Django 2.1.3 on 2019-01-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0040_auto_20190120_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'permissions': (('dbms_article_all', '访问项目列表'), ('dbms_article', '访问所有项目列表'), ('article_scan_all', '访问项目添加页'), ('article_scan_agree', '添加项目')), 'verbose_name_plural': '内部-员工'},
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '厂房'), (51, '科研')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='house_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
