# Generated by Django 2.1.3 on 2019-03-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0041_agrees_agree_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingorder',
            name='lending_balance',
            field=models.FloatField(default=0, verbose_name='_在保余额'),
        ),
    ]
