# Generated by Django 2.1.3 on 2019-01-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0041_auto_20190120_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_state',
            field=models.IntegerField(choices=[(1, '待反馈'), (2, '已反馈'), (3, '待上会'), (4, '已上会'), (5, '已签批'), (51, '已放完'), (61, '待变更'), (99, '已注销')], default=1, verbose_name='_项目状态'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='chattel_typ',
            field=models.IntegerField(choices=[(1, '存货'), (11, '设备')], default=1, verbose_name='动产种类'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draft_typ',
            field=models.IntegerField(choices=[(1, '银行承兑汇票'), (11, '商业承兑汇票'), (21, '支票')], default=1, verbose_name='票据种类'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='stock_typ',
            field=models.IntegerField(choices=[(1, '有限公司股权'), (11, '股份公司股份'), (21, '举办者权益')], default=1, verbose_name='股权性质'),
        ),
    ]
