# Generated by Django 2.1.3 on 2019-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0041_auto_20190521_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultstate',
            name='result_typ',
            field=models.IntegerField(choices=[(11, '股东会决议'), (21, '董事会决议'), (31, '声明书'), (41, '单身申明')], verbose_name='决议类型'),
        ),
    ]
