# Generated by Django 2.1.3 on 2019-01-20 11:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0042_auto_20190120_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='custom_buildor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='custom_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
        migrations.AddField(
            model_name='customes',
            name='custom_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='customes',
            name='lately_date',
            field=models.DateField(blank=True, null=True, verbose_name='最近调查'),
        ),
    ]
