# Generated by Django 2.1.3 on 2019-05-27 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0042_auto_20190521_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisals',
            name='compere',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.PROTECT, related_name='compere_employee', to=settings.AUTH_USER_MODEL, verbose_name='主持人'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='meeting_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_state',
            field=models.IntegerField(choices=[(11, '未签订'), (21, '已签订'), (31, '作废')], default=11, verbose_name='签订状态'),
        ),
        migrations.AlterField(
            model_name='customesc',
            name='decisionor',
            field=models.IntegerField(choices=[(11, '股东会'), (13, '合伙人会议'), (21, '董事会'), (23, '管理委员会')], default=11, verbose_name='决策机构'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (71, '仓储'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (71, '仓储'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 5, 27), verbose_name='补调日期'),
        ),
        migrations.AlterField(
            model_name='resultstate',
            name='result_typ',
            field=models.IntegerField(choices=[(11, '股东会决议'), (13, '合伙人会议决议'), (21, '董事会决议'), (23, '管委会决议'), (31, '声明书'), (41, '单身申明')], verbose_name='决议类型'),
        ),
    ]
