# Generated by Django 2.1.3 on 2019-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0043_articles_article_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperators',
            name='cooperator_accept',
            field=models.FloatField(default=0, verbose_name='_承兑余额'),
        ),
        migrations.AddField(
            model_name='cooperators',
            name='cooperator_back',
            field=models.FloatField(default=0, verbose_name='_保函余额'),
        ),
        migrations.AddField(
            model_name='cooperators',
            name='cooperator_flow',
            field=models.FloatField(default=0, verbose_name='_流贷余额'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_state',
            field=models.IntegerField(choices=[(11, '待签批'), (21, '已签批'), (31, '未落实'), (41, '已落实'), (51, '待变更'), (61, '已解保'), (99, '已注销')], default=11, verbose_name='合同状态'),
        ),
    ]
