# Generated by Django 2.1.3 on 2019-01-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0043_auto_20190120_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='pigeonhole_date',
            field=models.DateField(blank=True, null=True, verbose_name='归档日期'),
        ),
    ]
