# Generated by Django 2.1.3 on 2019-01-21 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0044_provides_pigeonhole_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='build_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
    ]
