# Generated by Django 2.1.3 on 2019-03-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0044_auto_20190311_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (61, '车库'), (71, '仓储'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_balance',
            field=models.FloatField(default=0, verbose_name='_在保余额'),
        ),
    ]
