# Generated by Django 2.1.3 on 2019-06-13 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0044_auto_20190527_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customesp',
            name='marital_status',
            field=models.IntegerField(choices=[(1, '已婚'), (11, '未婚'), (21, '离婚'), (31, '离婚'), (41, '丧偶')], default=1, verbose_name='婚姻状况'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='chattel_typ',
            field=models.IntegerField(choices=[(1, '存货'), (11, '机器设备'), (21, '医疗设备'), (99, '其他')], default=1, verbose_name='动产种类'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_name',
            field=models.IntegerField(blank=True, choices=[(1, '保证反担保合同'), (2, '不可撤销的反担保函'), (3, '抵押反担保合同'), (4, '应收账款质押反担保合同'), (5, '股权质押反担保合同'), (6, '质押反担保合同'), (9, '预售合同'), (21, '最高额保证反担保合同'), (23, '最高额抵押反担保合同'), (24, '最高额应收账款质押反担保合同'), (25, '最高额股权质押反担保合同'), (26, '最高额质押反担保合同'), (41, '保证合同'), (43, '抵押合同'), (44, '应收账款质押合同'), (45, '股权质押合同'), (46, '质押合同'), (59, '举办者权益转让协议')], null=True, verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_typ',
            field=models.IntegerField(choices=[(1, '企业担保'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (14, '在建工程抵押'), (15, '车辆抵押'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (34, '动产质押'), (41, '其他权利质押'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售'), (59, '其他预售')], verbose_name='合同类型'),
        ),
        migrations.AlterField(
            model_name='customesc',
            name='decisionor',
            field=models.IntegerField(choices=[(11, '股东会'), (13, '合伙人会议'), (15, '举办者会议'), (21, '董事会'), (23, '管理委员会')], default=11, verbose_name='决策机构'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (71, '仓储'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (71, '仓储'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 6, 13), verbose_name='补调日期'),
        ),
        migrations.AlterField(
            model_name='lendingsures',
            name='sure_typ',
            field=models.IntegerField(choices=[(1, '企业保证'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (14, '在建工程抵押'), (15, '车辆抵押'), (21, '房产顺位'), (22, '土地顺位'), (23, '在建工程顺位'), (24, '动产顺位'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (34, '动产质押'), (39, '其他权利质押'), (42, '房产监管'), (43, '土地监管'), (44, '票据监管'), (47, '动产监管'), (49, '其他监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售'), (59, '其他预售')], verbose_name='担保类型'),
        ),
        migrations.AlterField(
            model_name='resultstate',
            name='result_typ',
            field=models.IntegerField(choices=[(11, '股东会决议'), (13, '合伙人会议决议'), (15, '举办者会议决议'), (21, '董事会决议'), (23, '管委会决议'), (31, '声明书'), (41, '个人婚姻状况及财产申明')], verbose_name='决议类型'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_sty',
            field=models.IntegerField(blank=True, choices=[(1, '现场检查'), (11, '电话回访'), (61, '补调替代'), (62, '尽调替代')], null=True, verbose_name='保后方式'),
        ),
    ]
