# Generated by Django 2.1.3 on 2019-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0045_auto_20190613_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customesp',
            name='marital_status',
            field=models.IntegerField(choices=[(1, '未婚'), (11, '已婚'), (21, '离婚'), (31, '离婚'), (41, '丧偶')], default=1, verbose_name='婚姻状况'),
        ),
    ]
