# Generated by Django 2.1.3 on 2019-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0045_auto_20190314_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provides',
            name='provide_money',
            field=models.FloatField(default=0, verbose_name='放款金额'),
        ),
    ]
