# Generated by Django 2.1.3 on 2019-03-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0046_auto_20190314_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seal',
            name='seal_state',
            field=models.IntegerField(choices=[(1, '查询跟踪'), (3, '诉前保全'), (5, '首次首封'), (11, '首次轮封'), (21, '续查封'), (51, '解除查封'), (99, '注销')], default=1, verbose_name='查封状态'),
        ),
    ]
