# Generated by Django 2.1.3 on 2019-03-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0047_auto_20190315_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealup',
            name='sealup_remark',
            field=models.CharField(default='', max_length=64, verbose_name='备注'),
        ),
    ]
