# Generated by Django 2.1.3 on 2019-01-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0047_auto_20190122_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlequota',
            name='single_provide_sum',
        ),
        migrations.RemoveField(
            model_name='singlequota',
            name='single_repayment_sum',
        ),
    ]
