# Generated by Django 2.1.3 on 2019-03-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0048_auto_20190315_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealup',
            name='sealup_remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
    ]
