# Generated by Django 2.1.3 on 2019-06-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0048_auto_20190620_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='c_district', to='A_dbms.Districtes', verbose_name='所属区域'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customes',
            name='idustry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='c_idustry', to='A_dbms.Industries', verbose_name='所属行业'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customes',
            name='custom_state',
            field=models.IntegerField(choices=[(11, '担保客户'), (21, '反担保客户'), (99, '注销客户')], default=21, verbose_name='客户状态'),
        ),
    ]
