# Generated by Django 2.1.3 on 2019-01-23 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0049_provides_pigeonhole_explain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeonholes',
            name='pigeonholor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeonholor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
    ]
