# Generated by Django 2.1.3 on 2019-06-24 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0049_auto_20190620_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='new_old',
            field=models.IntegerField(choices=[(11, '续贷'), (21, '新增')], default=11, verbose_name='新增/续贷'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 6, 24), verbose_name='补调日期'),
        ),
    ]
