# Generated by Django 2.1.3 on 2019-03-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0049_auto_20190315_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_type',
            field=models.IntegerField(choices=[(1, '律师代理费'), (11, '案件受理费'), (21, '财产保全费'), (25, '评估费'), (31, '执行费'), (41, '公告费'), (99, '其他费用')], verbose_name='费用类型'),
        ),
    ]
