# Generated by Django 2.1.3 on 2019-01-23 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0050_auto_20190123_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provides',
            name='pigeonhole_date',
        ),
        migrations.RemoveField(
            model_name='provides',
            name='pigeonhole_explain',
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档')], default=1, verbose_name='_归档状态'),
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='pigeonhole_explain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='归档说明'),
        ),
        migrations.AddField(
            model_name='pigeonholes',
            name='pigeonhole_transfer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pigeonhole_transfer_employee', to=settings.AUTH_USER_MODEL, verbose_name='移交人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provides',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档')], default=1, verbose_name='_归档状态'),
        ),
    ]
