# Generated by Django 2.1.3 on 2019-06-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0050_auto_20190624_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provides',
            name='new_old',
            field=models.IntegerField(choices=[(11, '续贷'), (21, '新增')], verbose_name='新增/续贷'),
        ),
    ]
