# Generated by Django 2.1.3 on 2019-03-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0050_auto_20190315_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='dun',
            name='dun_balance',
            field=models.FloatField(default=0, verbose_name='_剩余金额'),
        ),
    ]
