# Generated by Django 2.1.3 on 2019-03-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0051_dun_dun_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sealup',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='sealup',
            name='sealup_date',
            field=models.DateField(blank=True, null=True, verbose_name='查封日期'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='single_quota_summary', to='A_dbms.Articles', verbose_name='纪要'),
        ),
    ]
