# Generated by Django 2.1.3 on 2019-06-25 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0051_auto_20190624_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='industries',
            name='cod_nam',
            field=models.CharField(default=1, max_length=48, verbose_name='代码名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 6, 25), verbose_name='补调日期'),
        ),
    ]
