# Generated by Django 2.1.3 on 2019-01-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0051_auto_20190123_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeonholes',
            name='implement',
            field=models.IntegerField(choices=[(1, '未归档'), (11, '退回'), (21, '暂存风控'), (31, '移交行政'), (41, '已归档')], default=1, verbose_name='归档状态'),
        ),
        migrations.AlterField(
            model_name='pigeonholes',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigeonhole_provide', to='A_dbms.Provides', verbose_name='放款'),
        ),
    ]
