# Generated by Django 2.1.3 on 2019-01-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0052_auto_20190123_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_status',
            field=models.IntegerField(choices=[(1, '在职'), (11, '离职')], default=1, verbose_name='_放款状态'),
        ),
    ]
