# Generated by Django 2.1.3 on 2019-03-19 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0052_auto_20190318_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_buildor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_type',
            field=models.IntegerField(choices=[(0, ''), (1, '同意'), (2, '复议'), (3, '不同意')], default=0, verbose_name='评委意见'),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='evaluate_state',
            field=models.IntegerField(choices=[(1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本'), (41, '拍卖评估')], default=1, verbose_name='评估方式'),
        ),
        migrations.AlterField(
            model_name='seal',
            name='sealor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sealor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '房产包'), (5, '土地'), (6, '在建工程'), (11, '应收'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '其他'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
    ]
