# Generated by Django 2.1.3 on 2019-07-02 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0052_auto_20190625_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='provides',
            name='new_amount',
            field=models.FloatField(default=0, verbose_name='新增金额'),
        ),
        migrations.AddField(
            model_name='provides',
            name='old_amount',
            field=models.FloatField(default=0, verbose_name='续贷金额'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='housebag_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (71, '仓储'), (72, '仓储用房及配送用房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (42, '非生产性工业用房'), (43, '厂房'), (44, '工业性科研用房'), (45, '工业'), (46, '非生产性工业科研用房'), (51, '科研'), (52, '车间'), (53, '消防通道'), (54, '倒班房'), (61, '车库'), (62, '车位'), (63, '首层机动车停车场'), (71, '仓储'), (72, '仓储用房及配送用房'), (81, '在建工程'), (91, '其他'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
        migrations.AlterField(
            model_name='investigate',
            name='inv_date',
            field=models.DateField(default=datetime.date(2019, 7, 2), verbose_name='补调日期'),
        ),
    ]
