# Generated by Django 2.1.3 on 2019-01-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0053_employees_employee_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'permissions': [('dbms_article_all', '访问项目列表'), ('dbms_article', '访问所有项目列表'), ('article_scan_all', '访问项目添加页'), ('article_scan_agree', '添加项目')], 'verbose_name_plural': '内部-员工'},
        ),
    ]
