# Generated by Django 2.1.3 on 2019-07-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0053_auto_20190702_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provides',
            name='new_old',
            field=models.IntegerField(choices=[(11, '续贷'), (21, '新增'), (99, '--')], default=99, verbose_name='新增/续贷'),
        ),
    ]
