# Generated by Django 2.1.3 on 2019-03-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0054_auto_20190319_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='coustruct_app',
            field=models.IntegerField(choices=[(91, '在建工程')], default=91, verbose_name='工程类别'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='coustruct_area',
            field=models.FloatField(verbose_name='工程面积'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='coustruct_locate',
            field=models.CharField(max_length=64, verbose_name='工程地址'),
        ),
    ]
