# Generated by Django 2.1.3 on 2019-01-23 09:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0054_auto_20190123_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housebag_locate', models.CharField(max_length=64, unique=True, verbose_name='房产坐落')),
                ('housebag_app', models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '厂房'), (51, '科研')], default=1, verbose_name='房产用途')),
                ('housebag_area', models.FloatField(verbose_name='建筑面积')),
                ('housebag_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('housebag_buildor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='housebag_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '权证-房产包',
                'db_table': 'dbms_housebag',
            },
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '房产包'), (5, '土地'), (11, '应收'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '动产'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
        migrations.AddField(
            model_name='housebag',
            name='warrant',
            field=models.ForeignKey(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='housebag_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
