# Generated by Django 2.1.3 on 2019-07-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0054_auto_20190702_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customes',
            name='counter_only',
        ),
    ]
