# Generated by Django 2.1.3 on 2019-03-19 03:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0055_auto_20190319_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_typ', models.IntegerField(choices=[(21, '合格证'), (31, '专利'), (41, '商标'), (71, '账户'), (99, '其他')], default=99, verbose_name='资产总类')),
                ('other_detail', models.TextField(verbose_name='具体描述')),
                ('otheror_date', models.DateField(default=datetime.date.today, verbose_name='创建日期')),
                ('other_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_custome', to='A_dbms.Customes', verbose_name='所有权人')),
                ('otheror', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='otheror_employee', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'db_table': 'dbms_others',
                'verbose_name_plural': '权证-其他',
            },
        ),
        migrations.AlterModelOptions(
            name='chattel',
            options={'verbose_name_plural': '权证-动产'},
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '房产包'), (5, '土地使用权'), (6, '在建工程'), (11, '应收账款'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '动产'), (55, '其他'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
        migrations.AddField(
            model_name='others',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 55}, on_delete=django.db.models.deletion.PROTECT, related_name='other_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
