# Generated by Django 2.1.3 on 2019-01-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0055_auto_20190123_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_date',
            field=models.DateField(blank=True, null=True, verbose_name='反馈日期'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 51}, on_delete=django.db.models.deletion.PROTECT, related_name='chattel_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 31}, on_delete=django.db.models.deletion.PROTECT, related_name='draft_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='draftextend',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extend_receiveable', to='A_dbms.Draft', verbose_name='票据'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 5}, on_delete=django.db.models.deletion.PROTECT, related_name='ground_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='warrant',
            field=models.ForeignKey(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='housebag_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='house_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 99}, on_delete=django.db.models.deletion.PROTECT, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 11}, on_delete=django.db.models.deletion.PROTECT, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='receiveextend',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extend_receiveable', to='A_dbms.Receivable', verbose_name='应收账款'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 21}, on_delete=django.db.models.deletion.PROTECT, related_name='stock_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 41}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
