# Generated by Django 2.1.3 on 2019-07-02 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0055_remove_customes_counter_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provides',
            name='new_old',
        ),
    ]
