# Generated by Django 2.1.3 on 2019-03-19 04:48

import A_dbms.models.m_warrant
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0056_auto_20190319_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattel',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 51}, on_delete=django.db.models.deletion.CASCADE, related_name='chattel_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 6}, on_delete=django.db.models.deletion.CASCADE, related_name='coustruct_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 31}, on_delete=django.db.models.deletion.CASCADE, related_name='draft_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='draftextend',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_draft', to='A_dbms.Draft', verbose_name='票据'),
        ),
        migrations.AlterField(
            model_name='grounds',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 5}, on_delete=django.db.models.deletion.CASCADE, related_name='ground_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='housebag',
            name='warrant',
            field=models.ForeignKey(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='housebag_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='house_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='agree',
            field=models.ForeignKey(limit_choices_to=A_dbms.models.m_warrant.limit_agree_choices, on_delete=django.db.models.deletion.CASCADE, related_name='ypothec_agree', to='A_dbms.Agrees', verbose_name='委托合同'),
        ),
        migrations.AlterField(
            model_name='hypothecs',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 99}, on_delete=django.db.models.deletion.CASCADE, related_name='ypothec_warrant', to='A_dbms.Warrants', verbose_name='他权证'),
        ),
        migrations.AlterField(
            model_name='others',
            name='other_typ',
            field=models.IntegerField(choices=[(11, '购房合同'), (21, '合格证'), (31, '专利'), (41, '商标'), (71, '账户'), (99, '其他')], default=99, verbose_name='资产总类'),
        ),
        migrations.AlterField(
            model_name='others',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 55}, on_delete=django.db.models.deletion.CASCADE, related_name='other_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AlterField(
            model_name='receivable',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 11}, on_delete=django.db.models.deletion.CASCADE, related_name='receive_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='receiveextend',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_receiveable', to='A_dbms.Receivable', verbose_name='应收账款'),
        ),
        migrations.AlterField(
            model_name='stockes',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 21}, on_delete=django.db.models.deletion.CASCADE, related_name='stock_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='warrant',
            field=models.OneToOneField(limit_choices_to={'warrant_typ': 41}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
        migrations.AlterField(
            model_name='warrants',
            name='warrant_typ',
            field=models.IntegerField(choices=[(1, '房产'), (2, '房产包'), (5, '土地'), (6, '在建工程'), (11, '应收账款'), (21, '股权'), (31, '票据'), (41, '车辆'), (51, '动产'), (55, '其他'), (99, '他权')], default=1, verbose_name='权证类型'),
        ),
    ]
