# Generated by Django 2.1.3 on 2019-01-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0056_auto_20190123_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '厂房'), (51, '科研'), (61, '车库')], default=1, verbose_name='房产用途'),
        ),
    ]
