# Generated by Django 2.1.3 on 2019-03-19 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0057_auto_20190319_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_custome', to='A_dbms.Customes', verbose_name='所有权人'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_warrant', to='A_dbms.Warrants', verbose_name='权证'),
        ),
    ]
