# Generated by Django 2.1.3 on 2019-01-24 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0057_auto_20190124_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agrees',
            options={'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='appraisals',
            options={'verbose_name_plural': '评审'},
        ),
        migrations.AlterModelOptions(
            name='lendingsures',
            options={'verbose_name_plural': '反担保'},
        ),
        migrations.AlterModelOptions(
            name='warrants',
            options={'verbose_name_plural': '权证'},
        ),
        migrations.AddField(
            model_name='evaluate',
            name='evaluate_state',
            field=models.IntegerField(choices=[(1, '机构评估'), (11, '机构预估'), (21, '综合询价'), (31, '购买成本')], default=1, verbose_name='评估方式'),
        ),
        migrations.AddField(
            model_name='evaluate',
            name='evaluator_date',
            field=models.DateField(default=datetime.date.today, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='evaluate',
            name='evaluate_date',
            field=models.DateField(verbose_name='评估日期'),
        ),
    ]
