# Generated by Django 2.1.3 on 2019-01-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0058_auto_20190124_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate',
            name='evaluate_explain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='评估说明'),
        ),
    ]
