# Generated by Django 2.1.3 on 2019-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0058_auto_20190319_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingsures',
            name='sure_typ',
            field=models.IntegerField(choices=[(1, '企业保证'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (14, '在建工程抵押'), (15, '车辆抵押'), (21, '房产顺位'), (22, '土地顺位'), (22, '在建工程顺位'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (41, '合格证监管'), (42, '房产监管'), (43, '土地监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='担保类型'),
        ),
    ]
