# Generated by Django 2.1.3 on 2019-03-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0059_auto_20190319_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendingsures',
            options={'ordering': ['sure_typ'], 'verbose_name_plural': '反担保'},
        ),
        migrations.AddField(
            model_name='cooperators',
            name='entrusted_loan',
            field=models.FloatField(default=0, verbose_name='_委贷余额'),
        ),
        migrations.AddField(
            model_name='cooperators',
            name='petty_loan',
            field=models.FloatField(default=0, verbose_name='_小贷余额'),
        ),
        migrations.AddField(
            model_name='customes',
            name='entrusted_loan',
            field=models.FloatField(default=0, verbose_name='_委贷余额'),
        ),
        migrations.AddField(
            model_name='customes',
            name='petty_loan',
            field=models.FloatField(default=0, verbose_name='_小贷余额'),
        ),
        migrations.AlterField(
            model_name='chattel',
            name='chattel_typ',
            field=models.IntegerField(choices=[(1, '存货'), (11, '机器设备'), (21, '合格证'), (31, '专利'), (41, '商标'), (71, '账户'), (99, '其他')], default=1, verbose_name='动产种类'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='counter_typ',
            field=models.IntegerField(choices=[(1, '企业担保'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (14, '在建工程抵押'), (15, '车辆抵押'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (34, '动产质押'), (41, '其他权利质押'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='合同类型'),
        ),
        migrations.AlterField(
            model_name='lendingsures',
            name='sure_typ',
            field=models.IntegerField(choices=[(1, '企业保证'), (2, '个人保证'), (11, '房产抵押'), (12, '土地抵押'), (13, '动产抵押'), (14, '在建工程抵押'), (15, '车辆抵押'), (21, '房产顺位'), (22, '土地顺位'), (23, '在建工程顺位'), (24, '动产顺位'), (31, '应收质押'), (32, '股权质押'), (33, '票据质押'), (34, '动产质押'), (39, '其他权利质押'), (42, '房产监管'), (43, '土地监管'), (44, '票据监管'), (47, '动产监管'), (49, '其他监管'), (51, '股权预售'), (52, '房产预售'), (53, '土地预售')], verbose_name='担保类型'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_typ',
            field=models.IntegerField(choices=[(1, '流贷'), (11, '承兑'), (21, '保函'), (31, '委贷'), (42, '小贷')], verbose_name='放款种类'),
        ),
        migrations.AlterField(
            model_name='singlequota',
            name='credit_model',
            field=models.IntegerField(choices=[(1, '流动资金贷款'), (2, '银行承兑汇票'), (3, '保函'), (4, '综合授信额度（含流贷、银承、保函）'), (31, '委托贷款'), (42, '小额贷款')], default=1, verbose_name='授信类型'),
        ),
    ]
