# Generated by Django 2.1.3 on 2019-01-24 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0060_auto_20190124_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='storages',
            name='storage_explain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='出入库说明'),
        ),
        migrations.AddField(
            model_name='warrants',
            name='storage_explain',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='出入库说明'),
        ),
        migrations.AlterField(
            model_name='storages',
            name='storage_date',
            field=models.DateField(default=datetime.date.today, verbose_name='出入库日期'),
        ),
    ]
