# Generated by Django 2.1.3 on 2019-03-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0060_auto_20190326_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='entrusted_loan',
            field=models.FloatField(default=0, verbose_name='_委贷余额'),
        ),
        migrations.AddField(
            model_name='branches',
            name='petty_loan',
            field=models.FloatField(default=0, verbose_name='_小贷余额'),
        ),
    ]
