# Generated by Django 2.1.3 on 2019-03-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0061_auto_20190326_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockes',
            name='ratio',
            field=models.FloatField(default=0, verbose_name='比例（%）'),
        ),
    ]
