# Generated by Django 2.1.3 on 2019-01-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0061_auto_20190124_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='house_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='楼盘名称'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (51, '科研'), (61, '车库'), (71, '仓储')], default=1, verbose_name='房产用途'),
        ),
    ]
