# Generated by Django 2.1.3 on 2019-01-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0062_auto_20190124_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='draft_typ',
        ),
        migrations.AddField(
            model_name='draftextend',
            name='draft_typ',
            field=models.IntegerField(choices=[(1, '银行承兑汇票'), (11, '商业承兑汇票'), (21, '支票')], default=1, verbose_name='票据种类'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='draft_detail',
            field=models.TextField(verbose_name='票据描述'),
        ),
    ]
