# Generated by Django 2.1.3 on 2019-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0062_stockes_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockes',
            name='ratio',
            field=models.FloatField(verbose_name='比例（%）'),
        ),
    ]
