# Generated by Django 2.1.3 on 2019-03-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0063_auto_20190327_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='managementor',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.PROTECT, related_name='manage_employee', to=settings.AUTH_USER_MODEL, verbose_name='管护经理'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='custom_buildor',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.PROTECT, related_name='custom_buildor_employee', to=settings.AUTH_USER_MODEL, verbose_name='_创建者'),
        ),
    ]
