# Generated by Django 2.1.3 on 2019-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0063_auto_20190125_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftextend',
            name='draft_drawer',
        ),
        migrations.AlterField(
            model_name='draftextend',
            name='draft_typ',
            field=models.IntegerField(choices=[(1, '电子银行承兑汇票'), (2, '普通银行承兑汇票'), (11, '电子商业承兑汇票'), (12, '普通商业承兑汇票'), (21, '支票')], default=1, verbose_name='票据种类'),
        ),
    ]
