# Generated by Django 2.1.3 on 2019-04-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0064_auto_20190327_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrees',
            name='agree_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='_合同名称'),
        ),
        migrations.AddField(
            model_name='counters',
            name='counter_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='_合同名称'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='agree_typ',
            field=models.IntegerField(choices=[(1, '单笔'), (2, '最高额'), (3, '保函'), (7, '小贷'), (41, '单笔(公证)'), (42, '最高额(公证)'), (47, '小贷(公证)')], verbose_name='合同种类'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='review_state',
            field=models.IntegerField(choices=[(1, '待保后'), (11, '待报告'), (21, '已完成'), (81, '自主保后')], default=21, verbose_name='_保后状态'),
        ),
        migrations.AlterField(
            model_name='provides',
            name='provide_typ',
            field=models.IntegerField(choices=[(1, '流贷'), (11, '承兑'), (21, '保函'), (31, '委贷'), (41, '小贷')], verbose_name='放款种类'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_state',
            field=models.IntegerField(choices=[(1, '待保后'), (11, '待报告'), (21, '已完成'), (81, '自主保后')], default=1, verbose_name='_保后状态'),
        ),
    ]
