# Generated by Django 2.1.3 on 2019-01-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0064_auto_20190125_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftextend',
            name='draft_amount',
            field=models.FloatField(default=0, verbose_name='票面金额'),
            preserve_default=False,
        ),
    ]
