# Generated by Django 2.1.3 on 2019-01-25 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0065_draftextend_draft_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftextend',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extend_draft', to='A_dbms.Draft', verbose_name='票据'),
        ),
    ]
