# Generated by Django 2.1.3 on 2019-04-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0065_auto_20190404_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agrees',
            name='agree_name',
            field=models.CharField(default=1, max_length=16, verbose_name='_合同名称'),
            preserve_default=False,
        ),
    ]
