# Generated by Django 2.1.3 on 2019-01-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0066_auto_20190125_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='银行简称'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_app',
            field=models.IntegerField(choices=[(1, '住宅'), (11, '商业'), (21, '办公'), (31, '公寓'), (41, '生产性工业用房'), (51, '科研'), (61, '车库'), (71, '仓储'), (99, '期房')], default=1, verbose_name='房产用途'),
        ),
    ]
