# Generated by Django 2.1.3 on 2019-01-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0067_auto_20190126_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='简称'),
        ),
    ]
