# Generated by Django 2.1.3 on 2019-01-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0068_customes_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customes',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='customes',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='客户简称'),
        ),
    ]
