# Generated by Django 2.1.3 on 2019-01-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0071_remove_customesc_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='institution_code',
        ),
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='放款银行'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='short_name',
            field=models.CharField(default='1', max_length=32, unique=True, verbose_name='银行简称'),
            preserve_default=False,
        ),
    ]
