# Generated by Django 2.1.3 on 2019-01-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0072_auto_20190126_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customesp',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_dbms.CustomesP', verbose_name='配偶'),
        ),
        migrations.AlterField(
            model_name='agrees',
            name='lending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agree_lending', to='A_dbms.LendingOrder', verbose_name='放款纪要'),
        ),
    ]
