# Generated by Django 2.1.3 on 2019-01-28 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0076_remove_customesp_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customesp',
            name='spouse',
            field=models.OneToOneField(blank=True, limit_choices_to={'genre': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_dbms.CustomesP', verbose_name='配偶'),
        ),
    ]
