# Generated by Django 2.1.3 on 2019-01-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0077_customesp_spouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='classification',
            field=models.IntegerField(choices=[(1, '正常'), (11, '关注'), (21, '次级'), (31, '可疑'), (41, '损失')], default=1, verbose_name='_风险分类'),
        ),
        migrations.AlterField(
            model_name='customesp',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_dbms.CustomesP', verbose_name='配偶'),
        ),
    ]
