# Generated by Django 2.1.3 on 2019-01-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_dbms', '0078_auto_20190128_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='customes',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='保后日期'),
        ),
        migrations.AddField(
            model_name='customes',
            name='review_plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='保后计划'),
        ),
        migrations.AddField(
            model_name='customes',
            name='review_state',
            field=models.IntegerField(choices=[(1, '待保后'), (11, '待报告'), (21, '已完成')], default=21, verbose_name='_保后状态'),
        ),
    ]
